import { randomUUID } from 'node:crypto';
import { db } from '@/lib/db';
import { recipes } from '@/lib/db/schema';

const systemRecipes = [
  // French Cuisine
  {
    name: 'Classic French Onion Soup',
    description: 'Rich and savory soup topped with melted Gruyère cheese',
    ingredients: [
      '6 large onions, thinly sliced',
      '4 tbsp butter',
      '2 cloves garlic, minced',
      '8 cups beef broth',
      '1 cup white wine',
      'Baguette slices',
      '2 cups Gruyère cheese, grated',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Caramelize onions in butter for 40 minutes',
      'Add garlic and cook for 2 minutes',
      'Add wine and reduce by half',
      'Add broth and simmer for 20 minutes',
      'Toast baguette slices',
      'Ladle soup into oven-safe bowls',
      'Top with bread and cheese',
      'Broil until cheese is bubbly',
    ],
    prepTime: 20,
    cookTime: 70,
    servings: 6,
    difficulty: 'medium',
    cuisine: 'French',
    tags: ['soup', 'French', 'comfort food', 'cheese'],
    images: [
      'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800&h=600&fit=crop',
    ],
    nutritionInfo: {
      calories: 420,
      protein: '18g',
      carbs: '45g',
      fat: '18g',
      fiber: '4g',
      sodium: '1200mg',
    },
  },
  {
    name: 'Coq au Vin',
    description: 'Traditional French braised chicken in red wine sauce',
    ingredients: [
      '1 whole chicken, cut into pieces',
      '200g bacon, diced',
      '12 pearl onions',
      '250g mushrooms',
      '3 cups red wine',
      '2 cups chicken stock',
      '3 tbsp flour',
      'Bouquet garni',
      'Salt and pepper',
    ],
    instructions: [
      'Brown bacon and set aside',
      'Brown chicken pieces in bacon fat',
      'Remove chicken, sauté onions and mushrooms',
      'Add flour to make roux',
      'Add wine and stock',
      'Return chicken and bacon',
      'Add bouquet garni',
      'Simmer for 1.5 hours',
    ],
    prepTime: 30,
    cookTime: 120,
    servings: 6,
    difficulty: 'hard',
    cuisine: 'French',
    tags: ['main course', 'French', 'wine', 'chicken'],
    images: ['https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800&h=600&fit=crop'],
    nutritionInfo: {
      calories: 520,
      protein: '35g',
      carbs: '15g',
      fat: '28g',
      fiber: '2g',
      sodium: '850mg',
    },
  },

  // Italian Cuisine
  {
    name: 'Osso Buco alla Milanese',
    description: 'Braised veal shanks with gremolata',
    ingredients: [
      '4 veal shanks',
      '1/2 cup flour',
      '4 tbsp olive oil',
      '1 onion, diced',
      '2 carrots, diced',
      '2 celery stalks, diced',
      '1 cup white wine',
      '2 cups beef broth',
      '400g crushed tomatoes',
      'Gremolata: lemon zest, garlic, parsley',
    ],
    instructions: [
      'Dredge veal in flour',
      'Brown veal on all sides',
      'Remove and sauté vegetables',
      'Add wine and reduce',
      'Add broth and tomatoes',
      'Return veal to pot',
      'Braise for 2 hours',
      'Serve with gremolata',
    ],
    prepTime: 25,
    cookTime: 150,
    servings: 4,
    difficulty: 'hard',
    cuisine: 'Italian',
    tags: ['main course', 'Italian', 'braised', 'veal'],
    images: ['https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=800&h=600&fit=crop'],
    nutritionInfo: {
      calories: 480,
      protein: '42g',
      carbs: '22g',
      fat: '20g',
      fiber: '3g',
      sodium: '750mg',
    },
  },
  {
    name: 'Homemade Gnocchi with Sage Butter',
    description: 'Pillowy potato dumplings in aromatic sage butter sauce',
    ingredients: [
      '2 lbs potatoes',
      '2 cups flour',
      '1 egg',
      '1 tsp salt',
      '8 tbsp butter',
      '12 fresh sage leaves',
      'Parmesan cheese',
    ],
    instructions: [
      'Boil potatoes until tender',
      'Rice potatoes while hot',
      'Mix with flour, egg, and salt',
      'Knead into smooth dough',
      'Roll and cut into gnocchi',
      'Boil until they float',
      'Brown butter with sage',
      'Toss gnocchi in sage butter',
    ],
    prepTime: 45,
    cookTime: 30,
    servings: 4,
    difficulty: 'medium',
    cuisine: 'Italian',
    tags: ['pasta', 'Italian', 'vegetarian', 'comfort food'],
    images: ['https://images.unsplash.com/photo-1609501676725-7186f017a4b7?w=800&h=600&fit=crop'],
    nutritionInfo: {
      calories: 380,
      protein: '10g',
      carbs: '58g',
      fat: '14g',
      fiber: '3g',
      sodium: '620mg',
    },
  },

  // Indian Cuisine
  {
    name: 'Chicken Biryani',
    description: 'Aromatic layered rice dish with spiced chicken',
    ingredients: [
      '500g chicken',
      '2 cups basmati rice',
      '1 cup yogurt',
      '2 onions, sliced',
      'Ginger-garlic paste',
      'Biryani spice mix',
      'Saffron in milk',
      'Mint leaves',
      'Ghee',
    ],
    instructions: [
      'Marinate chicken in yogurt and spices',
      'Fry onions until golden',
      'Cook chicken partially',
      'Parboil rice',
      'Layer rice and chicken',
      'Add saffron milk and fried onions',
      'Cover and cook on low heat',
      'Let it rest before serving',
    ],
    prepTime: 40,
    cookTime: 60,
    servings: 6,
    difficulty: 'hard',
    cuisine: 'Indian',
    tags: ['rice', 'Indian', 'spicy', 'main course'],
    images: [
      'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=800&h=600&fit=crop',
    ],
    nutritionInfo: {
      calories: 440,
      protein: '28g',
      carbs: '52g',
      fat: '12g',
      fiber: '2g',
      sodium: '680mg',
    },
  },
  {
    name: 'Palak Paneer',
    description: 'Creamy spinach curry with cottage cheese cubes',
    ingredients: [
      '500g spinach',
      '200g paneer',
      '2 tomatoes',
      '1 onion',
      '2 tbsp cream',
      'Ginger-garlic paste',
      'Green chilies',
      'Garam masala',
      'Cumin seeds',
    ],
    instructions: [
      'Blanch spinach and puree',
      'Fry paneer cubes',
      'Sauté cumin seeds',
      'Add onions and cook until soft',
      'Add tomatoes and spices',
      'Add spinach puree',
      'Simmer and add cream',
      'Add fried paneer',
    ],
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    difficulty: 'easy',
    cuisine: 'Indian',
    tags: ['curry', 'Indian', 'vegetarian', 'spinach'],
    images: ['https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&h=600&fit=crop'],
    nutritionInfo: {
      calories: 280,
      protein: '16g',
      carbs: '18g',
      fat: '18g',
      fiber: '4g',
      sodium: '520mg',
    },
  },
  {
    name: 'Masala Dosa',
    description: 'Crispy crepe with spiced potato filling',
    ingredients: [
      '2 cups dosa batter',
      'For filling: 4 potatoes, boiled',
      '1 onion',
      'Mustard seeds',
      'Curry leaves',
      'Turmeric',
      'Green chilies',
      'Oil for cooking',
    ],
    instructions: [
      'Prepare potato filling with spices',
      'Heat dosa pan',
      'Pour batter and spread thin',
      'Cook until crispy',
      'Add potato filling',
      'Fold dosa',
      'Serve with chutney and sambar',
    ],
    prepTime: 30,
    cookTime: 20,
    servings: 4,
    difficulty: 'medium',
    cuisine: 'Indian',
    tags: ['breakfast', 'Indian', 'vegetarian', 'crepe'],
    nutritionInfo: {
      calories: 320,
      protein: '8g',
      carbs: '58g',
      fat: '8g',
      fiber: '4g',
      sodium: '480mg',
    },
  },

  // Chinese Cuisine
  {
    name: 'Peking Duck',
    description: 'Crispy roasted duck with hoisin sauce and pancakes',
    ingredients: [
      '1 whole duck',
      'Maltose syrup',
      '5-spice powder',
      'Rice wine',
      'Thin pancakes',
      'Hoisin sauce',
      'Spring onions',
      'Cucumber julienne',
    ],
    instructions: [
      'Air-dry duck overnight',
      'Brush with maltose mixture',
      'Roast at high heat',
      'Reduce heat and continue roasting',
      'Rest and carve',
      'Serve with pancakes',
      'Add hoisin, spring onions, cucumber',
      'Roll and enjoy',
    ],
    prepTime: 1440,
    cookTime: 90,
    servings: 6,
    difficulty: 'hard',
    cuisine: 'Chinese',
    tags: ['duck', 'Chinese', 'roasted', 'special occasion'],
    nutritionInfo: {
      calories: 480,
      protein: '32g',
      carbs: '28g',
      fat: '26g',
      fiber: '1g',
      sodium: '920mg',
    },
  },
  {
    name: 'Mapo Tofu',
    description: 'Spicy Sichuan tofu with ground pork',
    ingredients: [
      '400g silken tofu',
      '200g ground pork',
      'Doubanjiang',
      'Sichuan peppercorns',
      'Garlic',
      'Ginger',
      'Spring onions',
      'Soy sauce',
      'Cornstarch slurry',
    ],
    instructions: [
      'Cut tofu into cubes',
      'Brown ground pork',
      'Add doubanjiang and aromatics',
      'Add broth',
      'Gently add tofu',
      'Simmer carefully',
      'Thicken with cornstarch',
      'Garnish with spring onions',
    ],
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: 'easy',
    cuisine: 'Chinese',
    tags: ['tofu', 'Chinese', 'spicy', 'Sichuan'],
    nutritionInfo: {
      calories: 320,
      protein: '22g',
      carbs: '12g',
      fat: '20g',
      fiber: '2g',
      sodium: '780mg',
    },
  },
  {
    name: 'Xiaolongbao (Soup Dumplings)',
    description: 'Delicate steamed dumplings filled with soup and pork',
    ingredients: [
      '300g flour',
      '500g pork',
      'Pork skin jelly',
      'Ginger',
      'Spring onions',
      'Shaoxing wine',
      'Soy sauce',
      'Sesame oil',
    ],
    instructions: [
      'Make dough and rest',
      'Prepare pork skin jelly',
      'Mix pork filling with jelly cubes',
      'Roll out wrappers',
      'Fill and pleat dumplings',
      'Steam for 8 minutes',
      'Serve with black vinegar and ginger',
    ],
    prepTime: 90,
    cookTime: 8,
    servings: 6,
    difficulty: 'hard',
    cuisine: 'Chinese',
    tags: ['dumplings', 'Chinese', 'steamed', 'soup'],
    nutritionInfo: {
      calories: 280,
      protein: '18g',
      carbs: '32g',
      fat: '10g',
      fiber: '1g',
      sodium: '620mg',
    },
  },

  // Korean Cuisine
  {
    name: 'Bibimbap',
    description: 'Mixed rice bowl with vegetables and gochujang',
    ingredients: [
      '2 cups rice',
      'Beef strips',
      'Spinach',
      'Bean sprouts',
      'Mushrooms',
      'Carrots',
      'Zucchini',
      'Eggs',
      'Gochujang sauce',
      'Sesame oil',
    ],
    instructions: [
      'Cook rice',
      'Marinate and cook beef',
      'Blanch and season each vegetable separately',
      'Fry eggs sunny-side up',
      'Arrange rice in bowls',
      'Top with vegetables and beef',
      'Add fried egg',
      'Serve with gochujang',
    ],
    prepTime: 30,
    cookTime: 30,
    servings: 4,
    difficulty: 'medium',
    cuisine: 'Korean',
    tags: ['rice bowl', 'Korean', 'vegetables', 'healthy'],
    nutritionInfo: {
      calories: 420,
      protein: '24g',
      carbs: '52g',
      fat: '14g',
      fiber: '5g',
      sodium: '680mg',
    },
  },
  {
    name: 'Korean Fried Chicken',
    description: 'Double-fried crispy chicken with sweet and spicy glaze',
    ingredients: [
      '1kg chicken wings',
      'Flour',
      'Cornstarch',
      'Soy sauce',
      'Gochugaru',
      'Honey',
      'Rice vinegar',
      'Garlic',
      'Ginger',
      'Sesame seeds',
    ],
    instructions: [
      'Marinate chicken',
      'Coat in flour-cornstarch mixture',
      'First fry at medium heat',
      'Rest for 3 minutes',
      'Second fry at high heat',
      'Make glaze with honey and gochugaru',
      'Toss chicken in glaze',
      'Garnish with sesame seeds',
    ],
    prepTime: 40,
    cookTime: 20,
    servings: 4,
    difficulty: 'medium',
    cuisine: 'Korean',
    tags: ['chicken', 'Korean', 'fried', 'spicy'],
    nutritionInfo: {
      calories: 520,
      protein: '32g',
      carbs: '38g',
      fat: '26g',
      fiber: '1g',
      sodium: '980mg',
    },
  },

  // Mexican Cuisine
  {
    name: 'Mole Negro',
    description: 'Complex Oaxacan black mole with chocolate',
    ingredients: [
      'Various dried chilies',
      'Chocolate',
      'Plantain',
      'Raisins',
      'Sesame seeds',
      'Spices',
      'Tomatoes',
      'Tomatillos',
      'Chicken',
      'Tortillas',
    ],
    instructions: [
      'Toast and soak chilies',
      'Char vegetables',
      'Toast spices and seeds',
      'Blend in batches',
      'Fry paste in lard',
      'Add broth slowly',
      'Simmer for hours',
      'Serve with chicken',
    ],
    prepTime: 60,
    cookTime: 240,
    servings: 8,
    difficulty: 'hard',
    cuisine: 'Mexican',
    tags: ['mole', 'Mexican', 'traditional', 'complex'],
    nutritionInfo: {
      calories: 460,
      protein: '28g',
      carbs: '42g',
      fat: '20g',
      fiber: '6g',
      sodium: '720mg',
    },
  },
  {
    name: 'Cochinita Pibil',
    description: 'Yucatan-style slow-roasted pork in banana leaves',
    ingredients: [
      '2kg pork shoulder',
      'Achiote paste',
      'Orange juice',
      'Lime juice',
      'Banana leaves',
      'Red onions',
      'Habanero peppers',
      'Cumin',
      'Oregano',
    ],
    instructions: [
      'Marinate pork in achiote mixture overnight',
      'Wrap in banana leaves',
      'Slow roast for 4 hours',
      'Shred meat',
      'Pickle red onions',
      'Serve with tortillas',
      'Top with pickled onions',
    ],
    prepTime: 30,
    cookTime: 240,
    servings: 8,
    difficulty: 'medium',
    cuisine: 'Mexican',
    tags: ['pork', 'Mexican', 'slow-cooked', 'Yucatan'],
    nutritionInfo: {
      calories: 380,
      protein: '32g',
      carbs: '12g',
      fat: '22g',
      fiber: '2g',
      sodium: '580mg',
    },
  },

  // Greek Cuisine
  {
    name: 'Moussaka',
    description: 'Layered eggplant and meat casserole with béchamel',
    ingredients: [
      '3 eggplants',
      '500g ground lamb',
      '2 onions',
      '400g tomatoes',
      'Red wine',
      'Cinnamon',
      'For béchamel: butter, flour, milk, eggs, nutmeg',
      'Parmesan cheese',
    ],
    instructions: [
      'Slice and salt eggplants',
      'Fry eggplant slices',
      'Make meat sauce with wine',
      'Prepare béchamel sauce',
      'Layer eggplant and meat',
      'Top with béchamel',
      'Bake until golden',
      'Rest before serving',
    ],
    prepTime: 45,
    cookTime: 60,
    servings: 8,
    difficulty: 'medium',
    cuisine: 'Greek',
    tags: ['casserole', 'Greek', 'eggplant', 'lamb'],
    nutritionInfo: {
      calories: 420,
      protein: '24g',
      carbs: '28g',
      fat: '24g',
      fiber: '4g',
      sodium: '680mg',
    },
  },
  {
    name: 'Spanakopita',
    description: 'Crispy phyllo pastry filled with spinach and feta',
    ingredients: [
      '1kg spinach',
      '400g feta cheese',
      'Phyllo dough',
      '3 eggs',
      'Dill',
      'Spring onions',
      'Olive oil',
      'Butter for brushing',
    ],
    instructions: [
      'Wilt and drain spinach thoroughly',
      'Mix with feta and eggs',
      'Add herbs',
      'Layer phyllo sheets with butter',
      'Add filling',
      'Top with more phyllo',
      'Score into pieces',
      'Bake until golden',
    ],
    prepTime: 30,
    cookTime: 45,
    servings: 12,
    difficulty: 'medium',
    cuisine: 'Greek',
    tags: ['pastry', 'Greek', 'spinach', 'vegetarian'],
    nutritionInfo: {
      calories: 280,
      protein: '12g',
      carbs: '22g',
      fat: '16g',
      fiber: '2g',
      sodium: '520mg',
    },
  },

  // Spanish Cuisine
  {
    name: 'Paella Valenciana',
    description: 'Traditional Spanish rice dish with rabbit and beans',
    ingredients: [
      'Bomba rice',
      'Rabbit',
      'Chicken',
      'Green beans',
      'Lima garrofó beans',
      'Tomatoes',
      'Saffron',
      'Rosemary',
      'Olive oil',
      'Lemon',
    ],
    instructions: [
      'Heat oil in paella pan',
      'Brown meat',
      'Add vegetables',
      'Make sofrito with tomatoes',
      'Add hot broth with saffron',
      'Add rice in cross pattern',
      'Do not stir',
      'Cook until socarrat forms',
    ],
    prepTime: 20,
    cookTime: 40,
    servings: 6,
    difficulty: 'medium',
    cuisine: 'Spanish',
    tags: ['rice', 'Spanish', 'traditional', 'Valencia'],
    nutritionInfo: {
      calories: 380,
      protein: '26g',
      carbs: '48g',
      fat: '10g',
      fiber: '3g',
      sodium: '620mg',
    },
  },
  {
    name: 'Gazpacho Andaluz',
    description: 'Refreshing cold tomato and vegetable soup',
    ingredients: [
      '1kg ripe tomatoes',
      '1 cucumber',
      '1 bell pepper',
      '2 garlic cloves',
      'Stale bread',
      'Olive oil',
      'Sherry vinegar',
      'Salt',
    ],
    instructions: [
      'Soak bread in water',
      'Blend tomatoes, cucumber, pepper',
      'Add soaked bread',
      'Add garlic, oil, vinegar',
      'Blend until smooth',
      'Strain if desired',
      'Chill for 2 hours',
      'Serve cold with garnishes',
    ],
    prepTime: 20,
    cookTime: 0,
    servings: 6,
    difficulty: 'easy',
    cuisine: 'Spanish',
    tags: ['soup', 'Spanish', 'cold', 'summer', 'vegetarian'],
    nutritionInfo: {
      calories: 120,
      protein: '3g',
      carbs: '18g',
      fat: '5g',
      fiber: '3g',
      sodium: '320mg',
    },
  },

  // Thai Cuisine
  {
    name: 'Pad Thai',
    description: 'Classic Thai stir-fried rice noodles',
    ingredients: [
      'Rice noodles',
      'Shrimp',
      'Tofu',
      'Eggs',
      'Bean sprouts',
      'Garlic chives',
      'Tamarind paste',
      'Fish sauce',
      'Palm sugar',
      'Peanuts',
      'Lime',
    ],
    instructions: [
      'Soak noodles',
      'Make tamarind sauce',
      'Stir-fry shrimp',
      'Push aside, scramble eggs',
      'Add noodles and sauce',
      'Toss quickly',
      'Add bean sprouts',
      'Serve with peanuts and lime',
    ],
    prepTime: 20,
    cookTime: 10,
    servings: 4,
    difficulty: 'medium',
    cuisine: 'Thai',
    tags: ['noodles', 'Thai', 'stir-fry', 'street food'],
    nutritionInfo: {
      calories: 380,
      protein: '18g',
      carbs: '52g',
      fat: '12g',
      fiber: '3g',
      sodium: '880mg',
    },
  },
  {
    name: 'Tom Yum Goong',
    description: 'Spicy and sour Thai soup with shrimp',
    ingredients: [
      'Large shrimp',
      'Lemongrass',
      'Galangal',
      'Kaffir lime leaves',
      'Thai chilies',
      'Mushrooms',
      'Tomatoes',
      'Fish sauce',
      'Lime juice',
      'Cilantro',
    ],
    instructions: [
      'Make broth with aromatics',
      'Strain aromatics',
      'Add mushrooms and tomatoes',
      'Add shrimp',
      'Season with fish sauce',
      'Add lime juice off heat',
      'Garnish with cilantro',
      'Serve immediately',
    ],
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    difficulty: 'easy',
    cuisine: 'Thai',
    tags: ['soup', 'Thai', 'spicy', 'seafood'],
    nutritionInfo: {
      calories: 180,
      protein: '22g',
      carbs: '12g',
      fat: '4g',
      fiber: '2g',
      sodium: '920mg',
    },
  },

  // Japanese Cuisine
  {
    name: 'Tonkotsu Ramen',
    description: 'Rich pork bone broth ramen with chashu pork',
    ingredients: [
      'Pork bones',
      'Ramen noodles',
      'Chashu pork belly',
      'Soft-boiled eggs',
      'Green onions',
      'Bamboo shoots',
      'Nori',
      'Garlic',
      'Ginger',
    ],
    instructions: [
      'Boil bones for 12-24 hours',
      'Prepare chashu pork',
      'Marinate soft-boiled eggs',
      'Cook noodles',
      'Assemble bowl with hot broth',
      'Top with chashu, egg, vegetables',
      'Add nori',
      'Serve immediately',
    ],
    prepTime: 60,
    cookTime: 720,
    servings: 4,
    difficulty: 'hard',
    cuisine: 'Japanese',
    tags: ['ramen', 'Japanese', 'pork', 'noodle soup'],
    nutritionInfo: {
      calories: 520,
      protein: '28g',
      carbs: '48g',
      fat: '24g',
      fiber: '2g',
      sodium: '1480mg',
    },
  },
  {
    name: 'Chirashi Bowl',
    description: 'Assorted sashimi over sushi rice',
    ingredients: [
      'Sushi rice',
      'Assorted sashimi fish',
      'Cucumber',
      'Avocado',
      'Shiso leaves',
      'Ikura',
      'Wasabi',
      'Pickled ginger',
      'Soy sauce',
      'Nori',
    ],
    instructions: [
      'Prepare sushi rice',
      'Cool rice properly',
      'Slice fish for sashimi',
      'Prepare vegetables',
      'Fill bowl with rice',
      'Arrange fish beautifully',
      'Garnish with ikura and shiso',
      'Serve with wasabi and soy sauce',
    ],
    prepTime: 30,
    cookTime: 20,
    servings: 4,
    difficulty: 'medium',
    cuisine: 'Japanese',
    tags: ['sushi', 'Japanese', 'raw fish', 'rice bowl'],
    nutritionInfo: {
      calories: 420,
      protein: '32g',
      carbs: '48g',
      fat: '12g',
      fiber: '3g',
      sodium: '680mg',
    },
  },

  // Vietnamese Cuisine
  {
    name: 'Pho Bo',
    description: 'Traditional Vietnamese beef noodle soup',
    ingredients: [
      'Beef bones',
      'Beef brisket',
      'Rice noodles',
      'Star anise',
      'Cinnamon',
      'Ginger',
      'Onions',
      'Fish sauce',
      'Bean sprouts',
      'Herbs',
      'Lime',
    ],
    instructions: [
      'Char ginger and onions',
      'Toast spices',
      'Simmer bones for 6 hours',
      'Cook brisket in broth',
      'Strain broth',
      'Cook noodles',
      'Slice beef thin',
      'Assemble and serve with herbs',
    ],
    prepTime: 30,
    cookTime: 360,
    servings: 6,
    difficulty: 'medium',
    cuisine: 'Vietnamese',
    tags: ['soup', 'Vietnamese', 'beef', 'noodles'],
    nutritionInfo: {
      calories: 380,
      protein: '28g',
      carbs: '42g',
      fat: '10g',
      fiber: '2g',
      sodium: '920mg',
    },
  },
  {
    name: 'Banh Xeo',
    description: 'Crispy Vietnamese crepe with shrimp and pork',
    ingredients: [
      'Rice flour',
      'Turmeric',
      'Coconut milk',
      'Shrimp',
      'Pork belly',
      'Bean sprouts',
      'Lettuce',
      'Herbs',
      'Fish sauce dipping sauce',
    ],
    instructions: [
      'Make crepe batter',
      'Heat skillet very hot',
      'Pour thin layer of batter',
      'Add shrimp and pork',
      'Add bean sprouts',
      'Cover to steam',
      'Fold in half when crispy',
      'Serve with lettuce and herbs',
    ],
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'medium',
    cuisine: 'Vietnamese',
    tags: ['crepe', 'Vietnamese', 'seafood', 'crispy'],
    nutritionInfo: {
      calories: 320,
      protein: '18g',
      carbs: '38g',
      fat: '12g',
      fiber: '3g',
      sodium: '680mg',
    },
  },

  // Middle Eastern Cuisine
  {
    name: 'Lamb Shawarma',
    description: 'Spiced lamb with tahini sauce in pita',
    ingredients: [
      '1kg lamb shoulder',
      'Shawarma spice blend',
      'Yogurt',
      'Pita bread',
      'Tahini sauce',
      'Tomatoes',
      'Cucumbers',
      'Red onions',
      'Parsley',
    ],
    instructions: [
      'Marinate lamb overnight',
      'Layer on vertical spit or roast',
      'Cook slowly, shaving edges',
      'Warm pita bread',
      'Make tahini sauce',
      'Prepare vegetables',
      'Assemble in pita',
      'Serve with pickles',
    ],
    prepTime: 30,
    cookTime: 120,
    servings: 6,
    difficulty: 'medium',
    cuisine: 'Middle Eastern',
    tags: ['lamb', 'Middle Eastern', 'sandwich', 'spiced'],
    nutritionInfo: {
      calories: 420,
      protein: '28g',
      carbs: '32g',
      fat: '20g',
      fiber: '3g',
      sodium: '720mg',
    },
  },
  {
    name: 'Falafel',
    description: 'Crispy chickpea fritters with herbs',
    ingredients: [
      'Dried chickpeas',
      'Parsley',
      'Cilantro',
      'Onion',
      'Garlic',
      'Cumin',
      'Coriander',
      'Baking powder',
      'Oil for frying',
    ],
    instructions: [
      'Soak chickpeas overnight',
      'Drain well',
      'Grind with herbs and spices',
      'Add baking powder',
      'Form into balls',
      'Deep fry until golden',
      'Serve in pita with tahini',
      'Add vegetables and pickles',
    ],
    prepTime: 720,
    cookTime: 20,
    servings: 6,
    difficulty: 'easy',
    cuisine: 'Middle Eastern',
    tags: ['vegetarian', 'Middle Eastern', 'fried', 'chickpeas'],
    nutritionInfo: {
      calories: 280,
      protein: '12g',
      carbs: '32g',
      fat: '12g',
      fiber: '6g',
      sodium: '420mg',
    },
  },

  // Moroccan Cuisine
  {
    name: 'Tagine of Lamb with Apricots',
    description: 'Slow-cooked Moroccan lamb stew with dried fruits',
    ingredients: [
      '1kg lamb shoulder',
      'Dried apricots',
      'Almonds',
      'Onions',
      'Cinnamon',
      'Ginger',
      'Saffron',
      'Honey',
      'Coriander',
      'Orange blossom water',
    ],
    instructions: [
      'Brown lamb pieces',
      'Sauté onions with spices',
      'Add lamb back',
      'Add liquid and simmer',
      'Add apricots halfway',
      'Toast almonds',
      'Finish with honey',
      'Garnish with almonds and cilantro',
    ],
    prepTime: 20,
    cookTime: 120,
    servings: 6,
    difficulty: 'medium',
    cuisine: 'Moroccan',
    tags: ['tagine', 'Moroccan', 'lamb', 'stew'],
    nutritionInfo: {
      calories: 420,
      protein: '32g',
      carbs: '28g',
      fat: '20g',
      fiber: '4g',
      sodium: '580mg',
    },
  },

  // Brazilian Cuisine
  {
    name: 'Feijoada',
    description: 'Brazilian black bean and pork stew',
    ingredients: [
      'Black beans',
      'Pork shoulder',
      'Bacon',
      'Sausages',
      'Pork ribs',
      'Bay leaves',
      'Garlic',
      'Onions',
      'Orange zest',
    ],
    instructions: [
      'Soak beans overnight',
      'Brown all meats',
      'Sauté aromatics',
      'Combine everything in pot',
      'Simmer for 2-3 hours',
      'Adjust seasoning',
      'Serve with rice',
      'Garnish with orange slices',
    ],
    prepTime: 30,
    cookTime: 180,
    servings: 8,
    difficulty: 'easy',
    cuisine: 'Brazilian',
    tags: ['stew', 'Brazilian', 'beans', 'pork'],
    nutritionInfo: {
      calories: 520,
      protein: '32g',
      carbs: '42g',
      fat: '24g',
      fiber: '12g',
      sodium: '880mg',
    },
  },

  // Peruvian Cuisine
  {
    name: 'Ceviche',
    description: 'Fresh fish marinated in citrus juice',
    ingredients: [
      '500g white fish',
      'Lime juice',
      'Red onions',
      'Cilantro',
      'Aji amarillo',
      'Sweet potato',
      'Corn',
      'Lettuce',
    ],
    instructions: [
      'Cut fish into cubes',
      'Marinate in lime juice',
      'Add sliced onions',
      'Add aji and cilantro',
      'Let cure for 15 minutes',
      'Serve immediately',
      'Garnish with sweet potato and corn',
      'Serve on lettuce',
    ],
    prepTime: 20,
    cookTime: 0,
    servings: 4,
    difficulty: 'easy',
    cuisine: 'Peruvian',
    tags: ['seafood', 'Peruvian', 'raw', 'citrus'],
    nutritionInfo: {
      calories: 220,
      protein: '28g',
      carbs: '18g',
      fat: '4g',
      fiber: '3g',
      sodium: '420mg',
    },
  },

  // Ethiopian Cuisine
  {
    name: 'Doro Wat',
    description: 'Spicy Ethiopian chicken stew',
    ingredients: [
      '1 whole chicken',
      'Berbere spice',
      '6 hard-boiled eggs',
      '4 onions',
      'Garlic',
      'Ginger',
      'Butter',
      'Red wine',
    ],
    instructions: [
      'Cook onions until very soft',
      'Add berbere spice',
      'Add garlic and ginger',
      'Add chicken pieces',
      'Simmer in wine and water',
      'Add hard-boiled eggs',
      'Cook until tender',
      'Serve with injera bread',
    ],
    prepTime: 30,
    cookTime: 90,
    servings: 6,
    difficulty: 'medium',
    cuisine: 'Ethiopian',
    tags: ['stew', 'Ethiopian', 'spicy', 'chicken'],
    nutritionInfo: {
      calories: 380,
      protein: '32g',
      carbs: '18g',
      fat: '20g',
      fiber: '3g',
      sodium: '620mg',
    },
  },

  // Russian Cuisine
  {
    name: 'Beef Stroganoff',
    description: 'Tender beef in creamy mushroom sauce',
    ingredients: [
      '600g beef tenderloin',
      '300g mushrooms',
      '1 onion',
      'Sour cream',
      'Beef broth',
      'Mustard',
      'Paprika',
      'Butter',
      'Flour',
    ],
    instructions: [
      'Cut beef into strips',
      'Sauté mushrooms and onions',
      'Remove vegetables',
      'Sear beef quickly',
      'Make roux with flour',
      'Add broth and mustard',
      'Return everything to pan',
      'Finish with sour cream',
    ],
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    difficulty: 'medium',
    cuisine: 'Russian',
    tags: ['beef', 'Russian', 'creamy', 'mushrooms'],
    nutritionInfo: {
      calories: 420,
      protein: '32g',
      carbs: '12g',
      fat: '28g',
      fiber: '2g',
      sodium: '580mg',
    },
  },
];

async function populateSystemRecipes() {
  console.log('🍳 Starting to populate system recipes...');

  try {
    for (const recipe of systemRecipes) {
      const recipeData = {
        id: randomUUID(),
        userId: 'system',
        name: recipe.name,
        description: recipe.description,
        ingredients: JSON.stringify(recipe.ingredients),
        instructions: JSON.stringify(recipe.instructions),
        prepTime: recipe.prepTime,
        cookTime: recipe.cookTime,
        servings: recipe.servings,
        difficulty: recipe.difficulty as 'easy' | 'medium' | 'hard',
        cuisine: recipe.cuisine,
        tags: JSON.stringify(recipe.tags),
        imageUrl: null,
        images: recipe.images ? JSON.stringify(recipe.images) : null,
        isAiGenerated: false,
        isPublic: true,
        isSystemRecipe: true,
        nutritionInfo: JSON.stringify(recipe.nutritionInfo),
        modelUsed: null,
        source: 'system',
      };

      await db.insert(recipes).values(recipeData);
      console.log(`✅ Added: ${recipe.name}`);
    }

    console.log(`\n🎉 Successfully added ${systemRecipes.length} system recipes!`);
  } catch (error) {
    console.error('❌ Error populating recipes:', error);
    throw error;
  }
}

// Execute if run directly
if (require.main === module) {
  populateSystemRecipes()
    .then(() => {
      console.log('✨ Done!');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Failed:', error);
      process.exit(1);
    });
}

export { populateSystemRecipes, systemRecipes };
