/**
 * Static Ingredient Substitution Library
 *
 * Comprehensive library of vetted ingredient substitutions for top 50 ingredients
 * Organized by category: fats, dairy, acids, proteins, aromatics, herbs & spices
 */

import type { StaticSubstitutionEntry } from './types';

/**
 * FATS & OILS
 */
const BUTTER: StaticSubstitutionEntry = {
  ingredient: 'butter',
  aliases: ['unsalted butter', 'salted butter', 'stick butter'],
  category: 'fat',
  substitutions: [
    {
      substitute_ingredient: 'coconut oil',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Similar fat content and melting point. Works excellently in baking for moisture and richness.',
      best_for: ['baking', 'cookies', 'cakes', 'sautéing'],
      avoid_for: ['frosting', 'buttercream'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
      cooking_adjustment: 'Use refined coconut oil to avoid coconut flavor. Solid at room temp like butter.',
    },
    {
      substitute_ingredient: 'olive oil',
      ratio: '3/4 cup oil = 1 cup butter',
      substitute_amount: '3/4 cup per 1 cup butter',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Healthier fat profile with heart-healthy monounsaturated fats. Best for savory dishes.',
      best_for: ['sautéing', 'roasting', 'savory baking'],
      avoid_for: ['sweet baking', 'frosting', 'pie crusts'],
      flavor_impact: 'noticeable',
      texture_impact: 'minimal',
      cooking_adjustment: 'Reduce amount by 25%. May make baked goods denser.',
    },
    {
      substitute_ingredient: 'applesauce',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Low-fat alternative that adds moisture. Reduces calories significantly.',
      best_for: ['muffins', 'quick breads', 'brownies', 'cake'],
      avoid_for: ['cookies', 'pie crust', 'sautéing', 'frosting'],
      flavor_impact: 'minimal',
      texture_impact: 'noticeable',
      cooking_adjustment: 'Baked goods will be denser and more cake-like. Reduce sugar slightly as applesauce adds sweetness.',
    },
    {
      substitute_ingredient: 'ghee',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.95,
      reason: 'Clarified butter with milk solids removed. Lactose-free with higher smoke point.',
      best_for: ['sautéing', 'high-heat cooking', 'baking'],
      avoid_for: [],
      flavor_impact: 'minimal',
      texture_impact: 'none',
      cooking_adjustment: 'Higher smoke point (485°F vs 350°F) makes it better for high-heat cooking.',
    },
    {
      substitute_ingredient: 'greek yogurt',
      ratio: '1/2 cup yogurt = 1 cup butter',
      substitute_amount: '1/2 cup per 1 cup butter',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Lower fat, higher protein alternative. Adds tanginess and moisture.',
      best_for: ['muffins', 'quick breads', 'pancakes'],
      avoid_for: ['cookies', 'pie crust', 'sautéing'],
      flavor_impact: 'noticeable',
      texture_impact: 'noticeable',
      cooking_adjustment: 'Reduce amount by 50%. Baked goods will be denser with slight tang.',
    },
  ],
};

const OLIVE_OIL: StaticSubstitutionEntry = {
  ingredient: 'olive oil',
  aliases: ['extra virgin olive oil', 'evoo', 'light olive oil'],
  category: 'fat',
  substitutions: [
    {
      substitute_ingredient: 'avocado oil',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Similar healthy fat profile with neutral flavor and very high smoke point (520°F).',
      best_for: ['high-heat cooking', 'grilling', 'roasting', 'baking'],
      avoid_for: [],
      flavor_impact: 'minimal',
      texture_impact: 'none',
      cooking_adjustment: 'Better for high-heat cooking than olive oil.',
    },
    {
      substitute_ingredient: 'canola oil',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Neutral flavor and high smoke point. More affordable option.',
      best_for: ['baking', 'frying', 'sautéing'],
      avoid_for: ['salad dressings', 'dips'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
      cooking_adjustment: 'Use when olive oil flavor is not desired.',
    },
    {
      substitute_ingredient: 'grapeseed oil',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Light, neutral oil with high smoke point (420°F). Good for cooking and baking.',
      best_for: ['sautéing', 'baking', 'salad dressings'],
      avoid_for: [],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'butter (melted)',
      ratio: '1 cup oil = 1 cup + 2 tbsp butter',
      substitute_amount: '1 cup + 2 tbsp melted butter per 1 cup oil',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Adds richness and flavor. Use for baking when butter flavor is desired.',
      best_for: ['baking', 'sautéing'],
      avoid_for: ['high-heat cooking', 'dairy-free diets'],
      flavor_impact: 'noticeable',
      texture_impact: 'minimal',
      cooking_adjustment: 'Increase amount slightly (112g butter = 100g oil). Lower smoke point.',
    },
  ],
};

const VEGETABLE_OIL: StaticSubstitutionEntry = {
  ingredient: 'vegetable oil',
  aliases: ['cooking oil'],
  category: 'fat',
  substitutions: [
    {
      substitute_ingredient: 'canola oil',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.95,
      reason: 'Virtually identical in use. Neutral flavor and similar smoke point.',
      best_for: ['baking', 'frying', 'sautéing'],
      avoid_for: [],
      flavor_impact: 'none',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'grapeseed oil',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Light, neutral flavor with high smoke point. Excellent all-purpose oil.',
      best_for: ['baking', 'frying', 'sautéing', 'salad dressing'],
      avoid_for: [],
      flavor_impact: 'none',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'sunflower oil',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Neutral taste, high smoke point (440°F). Good for all cooking methods.',
      best_for: ['baking', 'frying', 'sautéing'],
      avoid_for: [],
      flavor_impact: 'none',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'melted coconut oil',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.8,
      reason: 'Works well but may add slight coconut flavor. Use refined for neutral taste.',
      best_for: ['baking', 'sautéing'],
      avoid_for: ['high-heat frying'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
      cooking_adjustment: 'Use refined coconut oil to avoid coconut taste.',
    },
  ],
};

const COCONUT_OIL: StaticSubstitutionEntry = {
  ingredient: 'coconut oil',
  aliases: ['virgin coconut oil', 'refined coconut oil'],
  category: 'fat',
  substitutions: [
    {
      substitute_ingredient: 'butter',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Similar solid-at-room-temp properties. Works excellently in baking.',
      best_for: ['baking', 'cookies', 'pie crusts'],
      avoid_for: ['vegan recipes', 'dairy-free diets'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'vegetable oil',
      ratio: '1:1 (melted coconut oil)',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'When coconut oil is melted, can substitute with any neutral oil.',
      best_for: ['baking', 'sautéing'],
      avoid_for: ['recipes requiring solid fat'],
      flavor_impact: 'minimal',
      texture_impact: 'minimal',
      cooking_adjustment: 'If recipe calls for solid coconut oil, use cold butter instead.',
    },
    {
      substitute_ingredient: 'ghee',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Similar melting point and fat content. Lactose-free like coconut oil.',
      best_for: ['sautéing', 'baking', 'high-heat cooking'],
      avoid_for: ['vegan recipes'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
    },
  ],
};

/**
 * DAIRY PRODUCTS
 */
const MILK: StaticSubstitutionEntry = {
  ingredient: 'milk',
  aliases: ['whole milk', 'dairy milk', "cow's milk", '2% milk', 'skim milk'],
  category: 'dairy',
  substitutions: [
    {
      substitute_ingredient: 'almond milk',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Most popular dairy-free alternative. Neutral flavor works in most recipes.',
      best_for: ['baking', 'smoothies', 'cereal', 'coffee'],
      avoid_for: ['custards', 'puddings'],
      flavor_impact: 'minimal',
      texture_impact: 'minimal',
      cooking_adjustment: 'Use unsweetened for savory dishes. May be thinner than dairy milk.',
    },
    {
      substitute_ingredient: 'oat milk',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Creamy texture closest to dairy milk. Naturally sweet.',
      best_for: ['baking', 'coffee', 'hot chocolate', 'cream sauces'],
      avoid_for: [],
      flavor_impact: 'minimal',
      texture_impact: 'none',
      cooking_adjustment: 'Slightly sweeter than dairy milk. Great for barista-style drinks.',
    },
    {
      substitute_ingredient: 'soy milk',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'High protein content similar to dairy milk. Versatile for cooking and baking.',
      best_for: ['baking', 'cooking', 'smoothies'],
      avoid_for: ['soy allergies'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
      cooking_adjustment: 'Choose unsweetened for savory recipes.',
    },
    {
      substitute_ingredient: 'coconut milk (from carton)',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Dairy-free with slight coconut flavor. Different from canned coconut milk.',
      best_for: ['smoothies', 'curries', 'baking'],
      avoid_for: ['recipes where coconut flavor is undesirable'],
      flavor_impact: 'noticeable',
      texture_impact: 'minimal',
      cooking_adjustment: 'Use unsweetened. Not the same as canned coconut milk.',
    },
  ],
};

const HEAVY_CREAM: StaticSubstitutionEntry = {
  ingredient: 'heavy cream',
  aliases: ['heavy whipping cream', 'whipping cream', 'double cream'],
  category: 'dairy',
  substitutions: [
    {
      substitute_ingredient: 'half-and-half + butter',
      ratio: '1 cup = 7/8 cup half-and-half + 1/8 cup melted butter',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Mimics the fat content of heavy cream. Works for most applications.',
      best_for: ['soups', 'sauces', 'baking'],
      avoid_for: ['whipped cream'],
      flavor_impact: 'none',
      texture_impact: 'minimal',
      cooking_adjustment: "Won't whip as stiff as heavy cream.",
    },
    {
      substitute_ingredient: 'coconut cream',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Dairy-free, high-fat alternative. Can even be whipped.',
      best_for: ['whipped cream', 'curries', 'soups', 'desserts'],
      avoid_for: ['recipes where coconut flavor is undesirable'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
      cooking_adjustment: 'Chill can overnight, use thick cream from top. Has coconut flavor.',
    },
    {
      substitute_ingredient: 'evaporated milk',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Thicker than regular milk, lower fat than heavy cream. Good for cooking.',
      best_for: ['soups', 'sauces', 'coffee'],
      avoid_for: ['whipped cream', 'frostings'],
      flavor_impact: 'minimal',
      texture_impact: 'noticeable',
      cooking_adjustment: 'Less rich and cannot be whipped.',
    },
    {
      substitute_ingredient: 'greek yogurt + milk',
      ratio: '1 cup = 1/2 cup yogurt + 1/2 cup milk',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Lower fat alternative that adds tanginess. Increases protein.',
      best_for: ['soups', 'sauces', 'baking'],
      avoid_for: ['whipped cream', 'high-heat cooking'],
      flavor_impact: 'noticeable',
      texture_impact: 'noticeable',
      cooking_adjustment: 'Add at end of cooking to prevent curdling. Adds tang.',
    },
  ],
};

const SOUR_CREAM: StaticSubstitutionEntry = {
  ingredient: 'sour cream',
  aliases: ['soured cream'],
  category: 'dairy',
  substitutions: [
    {
      substitute_ingredient: 'greek yogurt',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.95,
      reason: 'Nearly identical in tang and texture. Higher protein, lower fat.',
      best_for: ['dips', 'toppings', 'baking', 'sauces'],
      avoid_for: [],
      flavor_impact: 'none',
      texture_impact: 'none',
      cooking_adjustment: 'Full-fat Greek yogurt is closest. Add at end for hot dishes.',
    },
    {
      substitute_ingredient: 'plain yogurt',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Similar tang and acidity. Slightly thinner than sour cream.',
      best_for: ['marinades', 'dressings', 'baking'],
      avoid_for: ['thick toppings'],
      flavor_impact: 'minimal',
      texture_impact: 'minimal',
      cooking_adjustment: 'May be thinner. Full-fat yogurt works best.',
    },
    {
      substitute_ingredient: 'cottage cheese (blended)',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'High protein alternative. Blend until smooth for similar texture.',
      best_for: ['dips', 'baking'],
      avoid_for: ['toppings without blending'],
      flavor_impact: 'minimal',
      texture_impact: 'minimal',
      cooking_adjustment: 'Must blend smooth. Add lemon juice for tang.',
    },
  ],
};

const EGGS: StaticSubstitutionEntry = {
  ingredient: 'eggs',
  aliases: ['whole eggs', 'large eggs'],
  category: 'protein',
  substitutions: [
    {
      substitute_ingredient: 'flax eggs',
      ratio: '1 egg = 1 tbsp ground flaxseed + 3 tbsp water',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Vegan egg replacer that binds well. Adds fiber and omega-3s.',
      best_for: ['muffins', 'pancakes', 'quick breads', 'cookies'],
      avoid_for: ['cakes', 'meringues', 'custards', 'soufflés'],
      flavor_impact: 'minimal',
      texture_impact: 'minimal',
      cooking_adjustment: 'Mix and let sit 5 minutes to gel. Adds slight nuttiness.',
    },
    {
      substitute_ingredient: 'applesauce',
      ratio: '1 egg = 1/4 cup applesauce',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Adds moisture and binding. Reduces fat and calories.',
      best_for: ['muffins', 'cakes', 'brownies'],
      avoid_for: ['cookies', 'meringues', 'scrambles'],
      flavor_impact: 'minimal',
      texture_impact: 'noticeable',
      cooking_adjustment: 'Makes baked goods denser and more moist. Reduce sugar slightly.',
    },
    {
      substitute_ingredient: 'mashed banana',
      ratio: '1 egg = 1/4 cup mashed banana',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Natural binder and adds moisture. Adds banana flavor.',
      best_for: ['pancakes', 'muffins', 'quick breads'],
      avoid_for: ['cookies', 'savory dishes', 'custards'],
      flavor_impact: 'noticeable',
      texture_impact: 'noticeable',
      cooking_adjustment: 'Adds banana flavor and sweetness. Dense texture.',
    },
  ],
};

/**
 * ACIDS & FLAVOR ENHANCERS
 */
const LEMON_JUICE: StaticSubstitutionEntry = {
  ingredient: 'lemon juice',
  aliases: ['fresh lemon juice', 'lemon'],
  category: 'acid',
  substitutions: [
    {
      substitute_ingredient: 'lime juice',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.95,
      reason: 'Similar acidity level (pH ~2). Slightly more bitter, equally bright.',
      best_for: ['dressings', 'marinades', 'beverages', 'sauces'],
      avoid_for: ['lemon-flavored desserts'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'white wine vinegar',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.8,
      reason: 'Similar acidity. Less citrus flavor but provides needed acid.',
      best_for: ['salad dressings', 'sauces', 'marinades'],
      avoid_for: ['desserts', 'beverages'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'apple cider vinegar',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Provides acidity with fruity undertone. More assertive flavor.',
      best_for: ['marinades', 'dressings', 'baking'],
      avoid_for: ['delicate dishes', 'beverages'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
      cooking_adjustment: 'Stronger flavor. May want to use slightly less.',
    },
  ],
};

const VINEGAR_WHITE: StaticSubstitutionEntry = {
  ingredient: 'white vinegar',
  aliases: ['distilled white vinegar', 'white wine vinegar'],
  category: 'acid',
  substitutions: [
    {
      substitute_ingredient: 'apple cider vinegar',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Similar acidity level. Slightly sweeter with apple notes.',
      best_for: ['pickling', 'baking', 'marinades', 'dressings'],
      avoid_for: ['recipes requiring neutral flavor'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'lemon juice',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Provides necessary acidity with citrus brightness.',
      best_for: ['baking', 'dressings', 'marinades'],
      avoid_for: ['pickling'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'rice vinegar',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Milder and slightly sweeter. Less acidic than white vinegar.',
      best_for: ['Asian dishes', 'dressings', 'sushi rice'],
      avoid_for: ['baking', 'pickling'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
      cooking_adjustment: 'Less acidic, may need to increase amount slightly.',
    },
  ],
};

/**
 * PROTEINS
 */
const CHICKEN_BREAST: StaticSubstitutionEntry = {
  ingredient: 'chicken breast',
  aliases: ['chicken breasts', 'boneless chicken breast', 'skinless chicken breast'],
  category: 'protein',
  substitutions: [
    {
      substitute_ingredient: 'chicken thighs',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'More flavorful and harder to dry out due to higher fat content.',
      best_for: ['grilling', 'roasting', 'braising', 'stir-frying'],
      avoid_for: ['recipes requiring white meat'],
      flavor_impact: 'minimal',
      texture_impact: 'minimal',
      cooking_adjustment: 'Slightly longer cooking time. More forgiving than breast.',
    },
    {
      substitute_ingredient: 'turkey breast',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Similar lean white meat with mild flavor. Slightly drier.',
      best_for: ['grilling', 'roasting', 'sandwiches'],
      avoid_for: [],
      flavor_impact: 'minimal',
      texture_impact: 'minimal',
      cooking_adjustment: 'Very similar cooking time. Can be dry if overcooked.',
    },
    {
      substitute_ingredient: 'pork tenderloin',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Lean, mild meat with similar texture. Slightly sweeter flavor.',
      best_for: ['roasting', 'grilling', 'stir-frying'],
      avoid_for: ['recipes where chicken flavor is important'],
      flavor_impact: 'noticeable',
      texture_impact: 'minimal',
    },
  ],
};

const GROUND_BEEF: StaticSubstitutionEntry = {
  ingredient: 'ground beef',
  aliases: ['ground chuck', 'hamburger', 'minced beef'],
  category: 'protein',
  substitutions: [
    {
      substitute_ingredient: 'ground turkey',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Leaner alternative with less fat. Healthier option.',
      best_for: ['tacos', 'meatballs', 'pasta sauce', 'burgers'],
      avoid_for: [],
      flavor_impact: 'minimal',
      texture_impact: 'minimal',
      cooking_adjustment: 'Add oil or butter for moisture. Cooks faster due to less fat.',
    },
    {
      substitute_ingredient: 'ground pork',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Similar fat content and texture. Slightly sweeter flavor.',
      best_for: ['meatballs', 'dumplings', 'pasta sauce'],
      avoid_for: ['traditional beef dishes like burgers'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'lentils (cooked)',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Plant-based, high-protein alternative. Significantly different texture.',
      best_for: ['tacos', 'pasta sauce', 'chili'],
      avoid_for: ['burgers', 'meatballs'],
      flavor_impact: 'significant',
      texture_impact: 'significant',
      cooking_adjustment: 'Season well to mimic meat flavor. Add cumin, paprika, soy sauce.',
    },
  ],
};

/**
 * AROMATICS
 */
const GARLIC: StaticSubstitutionEntry = {
  ingredient: 'garlic',
  aliases: ['fresh garlic', 'garlic cloves', 'garlic clove'],
  category: 'aromatic',
  substitutions: [
    {
      substitute_ingredient: 'garlic powder',
      ratio: '1 clove = 1/8 tsp powder',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Concentrated garlic flavor. More intense than fresh.',
      best_for: ['dry rubs', 'seasoning blends', 'baking'],
      avoid_for: ['raw applications', 'sautéing'],
      flavor_impact: 'minimal',
      texture_impact: 'significant',
      cooking_adjustment: 'Much more concentrated. Use sparingly.',
    },
    {
      substitute_ingredient: 'shallots',
      ratio: '1 clove garlic = 1 small shallot',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Milder, sweeter flavor with onion-garlic combination.',
      best_for: ['sauces', 'vinaigrettes', 'sautéing'],
      avoid_for: ['heavily garlic-flavored dishes'],
      flavor_impact: 'noticeable',
      texture_impact: 'minimal',
    },
    {
      substitute_ingredient: 'garlic scapes',
      ratio: '1 scape = 1 clove',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Milder, grassier garlic flavor. Seasonal availability.',
      best_for: ['pesto', 'stir-fries', 'sautéing'],
      avoid_for: ['strong garlic flavor needed'],
      flavor_impact: 'noticeable',
      texture_impact: 'noticeable',
      cooking_adjustment: 'Seasonal. Chop finely as they are fibrous.',
    },
  ],
};

const ONION: StaticSubstitutionEntry = {
  ingredient: 'onion',
  aliases: ['yellow onion', 'white onion', 'brown onion'],
  category: 'aromatic',
  substitutions: [
    {
      substitute_ingredient: 'shallots',
      ratio: '1 medium onion = 3-4 shallots',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Milder, sweeter flavor. More delicate than onions.',
      best_for: ['vinaigrettes', 'sauces', 'sautéing', 'roasting'],
      avoid_for: ['caramelized onions', 'onion rings'],
      flavor_impact: 'minimal',
      texture_impact: 'minimal',
    },
    {
      substitute_ingredient: 'leeks (white part)',
      ratio: '1 onion = 1 cup chopped leeks',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Milder, slightly sweet flavor. More delicate.',
      best_for: ['soups', 'quiche', 'sautéing'],
      avoid_for: ['raw applications', 'strong onion flavor needed'],
      flavor_impact: 'noticeable',
      texture_impact: 'minimal',
      cooking_adjustment: 'Clean thoroughly between layers. Milder flavor.',
    },
    {
      substitute_ingredient: 'onion powder',
      ratio: '1 medium onion = 1 tbsp onion powder',
      confidence: 'medium',
      confidence_score: 0.65,
      reason: 'Concentrated onion flavor without texture.',
      best_for: ['soups', 'sauces', 'dry rubs'],
      avoid_for: ['sautéing', 'caramelizing', 'texture important'],
      flavor_impact: 'minimal',
      texture_impact: 'significant',
      cooking_adjustment: 'No texture. Add early in cooking.',
    },
  ],
};

const GINGER: StaticSubstitutionEntry = {
  ingredient: 'ginger',
  aliases: ['fresh ginger', 'ginger root', 'gingerroot'],
  category: 'aromatic',
  substitutions: [
    {
      substitute_ingredient: 'ground ginger',
      ratio: '1 tbsp fresh = 1/4 tsp ground',
      confidence: 'high',
      confidence_score: 0.8,
      reason: 'More concentrated and spicier than fresh. Different flavor profile.',
      best_for: ['baking', 'spice rubs', 'soups'],
      avoid_for: ['stir-fries', 'fresh ginger tea'],
      flavor_impact: 'noticeable',
      texture_impact: 'significant',
      cooking_adjustment: 'Much more concentrated. Start with less.',
    },
    {
      substitute_ingredient: 'galangal',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Related root with citrusy, piney notes. Common in Thai cuisine.',
      best_for: ['Thai curries', 'soups', 'stir-fries'],
      avoid_for: ['Chinese dishes', 'baking'],
      flavor_impact: 'noticeable',
      texture_impact: 'minimal',
      cooking_adjustment: 'More citrusy and pine-like. Firmer texture.',
    },
    {
      substitute_ingredient: 'lemongrass',
      ratio: '1 tbsp ginger = 2 stalks lemongrass',
      confidence: 'low',
      confidence_score: 0.5,
      reason: 'Different flavor (citrusy) but provides aromatic freshness.',
      best_for: ['Southeast Asian dishes', 'soups', 'curries'],
      avoid_for: ['recipes where ginger flavor is essential'],
      flavor_impact: 'significant',
      texture_impact: 'noticeable',
      cooking_adjustment: 'Very different flavor. Only use in dishes that work with citrus notes.',
    },
  ],
};

/**
 * HERBS & SPICES
 */
const BASIL: StaticSubstitutionEntry = {
  ingredient: 'basil',
  aliases: ['fresh basil', 'sweet basil'],
  category: 'herb',
  substitutions: [
    {
      substitute_ingredient: 'oregano',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Italian herb with more assertive, earthy flavor.',
      best_for: ['pasta sauces', 'pizza', 'Italian dishes'],
      avoid_for: ['Thai basil dishes', 'pesto', 'fresh applications'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
      cooking_adjustment: 'More robust flavor. Oregano is stronger.',
    },
    {
      substitute_ingredient: 'spinach + mint',
      ratio: '1 cup basil = 1/2 cup spinach + 1/2 cup mint',
      confidence: 'medium',
      confidence_score: 0.65,
      reason: 'For pesto when basil unavailable. Mint adds aromatic component.',
      best_for: ['pesto'],
      avoid_for: ['cooking', 'marinades'],
      flavor_impact: 'noticeable',
      texture_impact: 'minimal',
      cooking_adjustment: 'Works primarily for pesto. Adjust mint to taste.',
    },
    {
      substitute_ingredient: 'dried basil',
      ratio: '1 tbsp fresh = 1 tsp dried',
      confidence: 'high',
      confidence_score: 0.75,
      reason: 'More concentrated when dried. Different texture.',
      best_for: ['sauces', 'soups', 'cooked dishes'],
      avoid_for: ['fresh applications', 'garnish', 'caprese'],
      flavor_impact: 'minimal',
      texture_impact: 'significant',
      cooking_adjustment: 'Add earlier in cooking. 3:1 ratio fresh to dried.',
    },
  ],
};

const OREGANO: StaticSubstitutionEntry = {
  ingredient: 'oregano',
  aliases: ['fresh oregano', 'dried oregano'],
  category: 'herb',
  substitutions: [
    {
      substitute_ingredient: 'marjoram',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Similar flavor but milder and sweeter. From same plant family.',
      best_for: ['Italian dishes', 'Greek dishes', 'roasted meats'],
      avoid_for: ['heavily oregano-flavored dishes'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'thyme',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Earthy, woodsy flavor. Different profile but works in Mediterranean dishes.',
      best_for: ['roasted vegetables', 'meats', 'soups'],
      avoid_for: ['pizza', 'pasta sauces'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'basil + thyme',
      ratio: '1 tsp oregano = 1/2 tsp basil + 1/2 tsp thyme',
      confidence: 'medium',
      confidence_score: 0.65,
      reason: 'Combination mimics oregano complexity.',
      best_for: ['Italian dishes', 'tomato sauces'],
      avoid_for: ['simple dishes'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
  ],
};

const CILANTRO: StaticSubstitutionEntry = {
  ingredient: 'cilantro',
  aliases: ['fresh cilantro', 'coriander leaves', 'chinese parsley'],
  category: 'herb',
  substitutions: [
    {
      substitute_ingredient: 'parsley',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.65,
      reason: 'Similar fresh, green flavor without cilantro soapy notes.',
      best_for: ['garnish', 'sauces', 'salads'],
      avoid_for: ['Mexican', 'Thai dishes where cilantro is prominent'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
      cooking_adjustment: 'Lacks distinctive cilantro flavor. Good for cilantro-haters.',
    },
    {
      substitute_ingredient: 'culantro',
      ratio: '1/4 culantro = 1 cilantro',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Related plant with similar but much stronger flavor.',
      best_for: ['Latin American', 'Caribbean dishes'],
      avoid_for: ['delicate dishes'],
      flavor_impact: 'minimal',
      texture_impact: 'noticeable',
      cooking_adjustment: 'Much stronger. Use 1/4 the amount.',
    },
    {
      substitute_ingredient: 'basil + lime zest',
      ratio: '1 cup cilantro = 1 cup basil + 1 tsp lime zest',
      confidence: 'low',
      confidence_score: 0.5,
      reason: 'Provides freshness and citrus notes cilantro brings.',
      best_for: ['salads', 'fresh applications'],
      avoid_for: ['authentic Mexican/Thai dishes'],
      flavor_impact: 'significant',
      texture_impact: 'minimal',
      cooking_adjustment: 'Different flavor profile but adds brightness.',
    },
  ],
};

const PARSLEY: StaticSubstitutionEntry = {
  ingredient: 'parsley',
  aliases: ['fresh parsley', 'flat-leaf parsley', 'italian parsley', 'curly parsley'],
  category: 'herb',
  substitutions: [
    {
      substitute_ingredient: 'cilantro',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Fresh, green flavor. Different taste profile.',
      best_for: ['garnish', 'fresh sauces', 'salads'],
      avoid_for: ['Italian dishes', 'those who dislike cilantro'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'chervil',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.8,
      reason: 'Delicate, slightly anise flavor. Similar appearance.',
      best_for: ['French dishes', 'sauces', 'garnish'],
      avoid_for: [],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'celery leaves',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.65,
      reason: 'Similar fresh, slightly bitter flavor. Often discarded but usable.',
      best_for: ['stocks', 'soups', 'garnish'],
      avoid_for: ['raw applications', 'delicate dishes'],
      flavor_impact: 'noticeable',
      texture_impact: 'minimal',
      cooking_adjustment: 'More celery flavor. Stronger taste than parsley.',
    },
  ],
};

const CUMIN: StaticSubstitutionEntry = {
  ingredient: 'cumin',
  aliases: ['ground cumin', 'cumin seeds', 'cumin powder'],
  category: 'spice',
  substitutions: [
    {
      substitute_ingredient: 'caraway seeds',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Similar earthy, warm flavor. Slightly more licorice notes.',
      best_for: ['bread', 'cabbage dishes', 'European recipes'],
      avoid_for: ['Mexican', 'Indian dishes'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'ground coriander',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.65,
      reason: 'Citrusy, warm flavor. Often paired with cumin.',
      best_for: ['curry', 'Indian dishes', 'marinades'],
      avoid_for: ['chili', 'taco seasoning'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
      cooking_adjustment: 'Sweeter, more citrus. Lacks cumin earthiness.',
    },
    {
      substitute_ingredient: 'chili powder',
      ratio: '1/2 chili powder + 1/2 paprika',
      confidence: 'low',
      confidence_score: 0.5,
      reason: 'Chili powder often contains cumin. Adds heat.',
      best_for: ['Mexican dishes', 'chili'],
      avoid_for: ['Indian dishes', 'recipes needing pure cumin'],
      flavor_impact: 'significant',
      texture_impact: 'none',
      cooking_adjustment: 'Adds heat and other spices. Not a clean substitute.',
    },
  ],
};

const PAPRIKA: StaticSubstitutionEntry = {
  ingredient: 'paprika',
  aliases: ['sweet paprika', 'smoked paprika', 'hungarian paprika'],
  category: 'spice',
  substitutions: [
    {
      substitute_ingredient: 'cayenne pepper',
      ratio: '1 tsp paprika = 1/4 tsp cayenne',
      confidence: 'medium',
      confidence_score: 0.6,
      reason: 'Provides red color and heat. Much spicier than paprika.',
      best_for: ['dishes needing heat', 'color'],
      avoid_for: ['mild dishes', 'sweet paprika flavor'],
      flavor_impact: 'significant',
      texture_impact: 'none',
      cooking_adjustment: 'Much spicier. Use 1/4 amount. Add gradually.',
    },
    {
      substitute_ingredient: 'chili powder',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.65,
      reason: 'Contains paprika plus other spices. More complex.',
      best_for: ['Mexican dishes', 'chili'],
      avoid_for: ['Hungarian dishes', 'pure paprika flavor'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
      cooking_adjustment: 'Contains cumin and other spices.',
    },
    {
      substitute_ingredient: 'tomato powder',
      ratio: '1:1',
      confidence: 'low',
      confidence_score: 0.5,
      reason: 'Provides red color and umami. Different flavor.',
      best_for: ['color', 'savory dishes'],
      avoid_for: ['smoky flavor needed', 'sweet paprika'],
      flavor_impact: 'significant',
      texture_impact: 'minimal',
      cooking_adjustment: 'More savory, less sweet. Different flavor profile.',
    },
  ],
};

const CINNAMON: StaticSubstitutionEntry = {
  ingredient: 'cinnamon',
  aliases: ['ground cinnamon', 'cinnamon powder', 'cinnamon sticks'],
  category: 'spice',
  substitutions: [
    {
      substitute_ingredient: 'nutmeg',
      ratio: '1 tsp cinnamon = 1/2 tsp nutmeg',
      confidence: 'medium',
      confidence_score: 0.65,
      reason: 'Warm spice with sweet, nutty flavor. More pungent than cinnamon.',
      best_for: ['baking', 'pumpkin spice', 'eggnog'],
      avoid_for: ['cinnamon rolls', 'snickerdoodles'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
      cooking_adjustment: 'Use half the amount. Nutmeg is stronger.',
    },
    {
      substitute_ingredient: 'allspice',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Combination flavor of cinnamon, nutmeg, cloves.',
      best_for: ['baking', 'savory dishes', 'Caribbean cuisine'],
      avoid_for: ['pure cinnamon flavor needed'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
      cooking_adjustment: 'More complex flavor with clove notes.',
    },
    {
      substitute_ingredient: 'cardamom',
      ratio: '1 tsp cinnamon = 1/2 tsp cardamom',
      confidence: 'low',
      confidence_score: 0.5,
      reason: 'Warm, sweet, citrusy spice. Different flavor profile.',
      best_for: ['Indian dishes', 'Scandinavian baking', 'chai'],
      avoid_for: ['American baking', 'cinnamon flavor essential'],
      flavor_impact: 'significant',
      texture_impact: 'none',
      cooking_adjustment: 'Very different flavor. More floral and citrusy.',
    },
  ],
};

/**
 * SWEETENERS
 */
const SUGAR: StaticSubstitutionEntry = {
  ingredient: 'sugar',
  aliases: ['white sugar', 'granulated sugar', 'cane sugar'],
  category: 'sweetener',
  substitutions: [
    {
      substitute_ingredient: 'honey',
      ratio: '1 cup sugar = 3/4 cup honey',
      confidence: 'high',
      confidence_score: 0.8,
      reason: 'Natural sweetener, more intense sweetness. Adds moisture.',
      best_for: ['baking', 'glazes', 'marinades'],
      avoid_for: ['meringues', 'hard candies'],
      flavor_impact: 'noticeable',
      texture_impact: 'minimal',
      cooking_adjustment: 'Reduce liquid by 1/4 cup per cup honey. Reduce oven temp by 25°F.',
    },
    {
      substitute_ingredient: 'maple syrup',
      ratio: '1 cup sugar = 3/4 cup maple syrup',
      confidence: 'high',
      confidence_score: 0.75,
      reason: 'Natural sweetener with distinct flavor. Adds moisture.',
      best_for: ['pancakes', 'baking', 'glazes'],
      avoid_for: ['meringues', 'recipes where maple flavor unwanted'],
      flavor_impact: 'noticeable',
      texture_impact: 'minimal',
      cooking_adjustment: 'Reduce liquid by 3 tbsp per cup syrup.',
    },
    {
      substitute_ingredient: 'coconut sugar',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Lower glycemic index. Slight caramel flavor.',
      best_for: ['baking', 'beverages', 'granola'],
      avoid_for: ['white cakes', 'meringues'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
      cooking_adjustment: 'Slightly less sweet. May add light brown color.',
    },
  ],
};

const BROWN_SUGAR: StaticSubstitutionEntry = {
  ingredient: 'brown sugar',
  aliases: ['light brown sugar', 'dark brown sugar', 'packed brown sugar'],
  category: 'sweetener',
  substitutions: [
    {
      substitute_ingredient: 'white sugar + molasses',
      ratio: '1 cup = 1 cup white sugar + 1 tbsp molasses',
      confidence: 'high',
      confidence_score: 0.95,
      reason: 'Brown sugar is literally white sugar + molasses.',
      best_for: ['all applications'],
      avoid_for: [],
      flavor_impact: 'none',
      texture_impact: 'none',
      cooking_adjustment: 'Mix well. Use 2 tbsp molasses for dark brown sugar.',
    },
    {
      substitute_ingredient: 'coconut sugar',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Similar caramel notes and moisture content.',
      best_for: ['baking', 'sauces', 'glazes'],
      avoid_for: [],
      flavor_impact: 'minimal',
      texture_impact: 'minimal',
    },
    {
      substitute_ingredient: 'white sugar',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Works but loses molasses flavor and moisture.',
      best_for: ['recipes where molasses flavor not critical'],
      avoid_for: ['chocolate chip cookies', 'gingerbread'],
      flavor_impact: 'noticeable',
      texture_impact: 'minimal',
      cooking_adjustment: 'Less moisture and caramel flavor.',
    },
  ],
};

/**
 * CONDIMENTS & SAUCES
 */
const MAYONNAISE: StaticSubstitutionEntry = {
  ingredient: 'mayonnaise',
  aliases: ['mayo'],
  category: 'condiment',
  substitutions: [
    {
      substitute_ingredient: 'greek yogurt',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Similar creamy texture with tangy flavor. Much healthier alternative.',
      best_for: ['dressings', 'dips', 'sandwiches'],
      avoid_for: ['hot dishes (may curdle)'],
      flavor_impact: 'minimal',
      texture_impact: 'minimal',
      cooking_adjustment: 'Add at end for hot dishes to prevent curdling.',
    },
    {
      substitute_ingredient: 'sour cream',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Similar tang and creaminess. Slightly thinner consistency.',
      best_for: ['dips', 'dressings', 'cold salads'],
      avoid_for: [],
      flavor_impact: 'minimal',
      texture_impact: 'minimal',
    },
    {
      substitute_ingredient: 'avocado (mashed)',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Healthy fat alternative with creamy texture. Different flavor profile.',
      best_for: ['sandwiches', 'wraps', 'spreads'],
      avoid_for: ['baking', 'coleslaw'],
      flavor_impact: 'noticeable',
      texture_impact: 'minimal',
      cooking_adjustment: 'Best used immediately to prevent browning.',
    },
  ],
};

const DIJON_MUSTARD: StaticSubstitutionEntry = {
  ingredient: 'dijon mustard',
  aliases: ['dijon', 'grey poupon'],
  category: 'condiment',
  substitutions: [
    {
      substitute_ingredient: 'whole grain mustard',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Similar tang and heat. Adds texture from mustard seeds.',
      best_for: ['vinaigrettes', 'marinades', 'sauces'],
      avoid_for: ['smooth sauces'],
      flavor_impact: 'minimal',
      texture_impact: 'noticeable',
    },
    {
      substitute_ingredient: 'yellow mustard',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Sharper, more acidic. Less refined flavor than Dijon.',
      best_for: ['marinades', 'dressings'],
      avoid_for: ['delicate sauces', 'French cuisine'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
      cooking_adjustment: 'Add slightly less as yellow mustard is more acidic.',
    },
    {
      substitute_ingredient: 'horseradish',
      ratio: '1 tbsp mustard = 1 tsp horseradish',
      confidence: 'low',
      confidence_score: 0.5,
      reason: 'Similar heat and pungency. Much stronger.',
      best_for: ['sauces', 'roast beef'],
      avoid_for: ['vinaigrettes', 'most applications'],
      flavor_impact: 'significant',
      texture_impact: 'noticeable',
      cooking_adjustment: 'Use 1/3 the amount. Much more intense.',
    },
  ],
};

const SOY_SAUCE: StaticSubstitutionEntry = {
  ingredient: 'soy sauce',
  aliases: ['shoyu', 'tamari'],
  category: 'condiment',
  substitutions: [
    {
      substitute_ingredient: 'tamari',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.95,
      reason: 'Nearly identical flavor. Gluten-free alternative to soy sauce.',
      best_for: ['all applications'],
      avoid_for: [],
      flavor_impact: 'none',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'coconut aminos',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Soy-free, gluten-free. Slightly sweeter with similar umami.',
      best_for: ['stir-fries', 'marinades', 'dressings'],
      avoid_for: ['authentic Asian dishes'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
      cooking_adjustment: 'Slightly sweeter. May want to reduce other sweeteners.',
    },
    {
      substitute_ingredient: 'worcestershire sauce',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.65,
      reason: 'Provides umami depth. Different flavor profile with more complexity.',
      best_for: ['marinades', 'stews', 'gravies'],
      avoid_for: ['Asian dishes', 'sushi'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
    },
  ],
};

const WORCESTERSHIRE_SAUCE: StaticSubstitutionEntry = {
  ingredient: 'worcestershire sauce',
  aliases: ['worcester sauce', 'lea & perrins'],
  category: 'condiment',
  substitutions: [
    {
      substitute_ingredient: 'soy sauce + vinegar',
      ratio: '1 tbsp worcestershire = 1 tbsp soy sauce + 1 tsp vinegar',
      confidence: 'high',
      confidence_score: 0.8,
      reason: 'Mimics umami and tangy components. Add dash of hot sauce for complexity.',
      best_for: ['marinades', 'stews', 'sauces'],
      avoid_for: ['Bloody Marys', 'Caesar dressing'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'balsamic vinegar',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Provides depth and tang. Sweeter than worcestershire.',
      best_for: ['marinades', 'glazes'],
      avoid_for: ['traditional British dishes'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'fish sauce',
      ratio: '1 tbsp worcestershire = 2 tsp fish sauce',
      confidence: 'medium',
      confidence_score: 0.65,
      reason: 'Strong umami flavor. Much more pungent.',
      best_for: ['Asian-inspired dishes', 'marinades'],
      avoid_for: ['traditional recipes', 'seafood-averse diners'],
      flavor_impact: 'significant',
      texture_impact: 'none',
      cooking_adjustment: 'Use less (2/3 amount). Very potent.',
    },
  ],
};

/**
 * ADDITIONAL VEGETABLES
 */
const CELERY: StaticSubstitutionEntry = {
  ingredient: 'celery',
  aliases: ['celery stalks', 'celery ribs'],
  category: 'vegetable',
  substitutions: [
    {
      substitute_ingredient: 'fennel',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Similar crunch and texture. Adds subtle anise flavor.',
      best_for: ['soups', 'stews', 'salads'],
      avoid_for: ['recipes where celery flavor is important'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'bok choy stems',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Similar crunch and water content. Milder flavor.',
      best_for: ['stir-fries', 'soups', 'stocks'],
      avoid_for: ['raw applications', 'Western cuisine'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'celery seed',
      ratio: '1 stalk = 1/2 tsp celery seed',
      confidence: 'low',
      confidence_score: 0.5,
      reason: 'Provides celery flavor without texture. Much more concentrated.',
      best_for: ['soups', 'stews', 'dry rubs'],
      avoid_for: ['salads', 'dishes needing crunch'],
      flavor_impact: 'minimal',
      texture_impact: 'significant',
      cooking_adjustment: 'No texture. Use sparingly as very concentrated.',
    },
  ],
};

const CARROTS: StaticSubstitutionEntry = {
  ingredient: 'carrots',
  aliases: ['carrot'],
  category: 'vegetable',
  substitutions: [
    {
      substitute_ingredient: 'parsnips',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Similar texture and sweetness. Slightly earthier flavor.',
      best_for: ['roasting', 'soups', 'stews'],
      avoid_for: ['raw salads', 'carrot cake'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'sweet potato',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Similar sweetness and color. Softer texture when cooked.',
      best_for: ['soups', 'purees', 'roasting'],
      avoid_for: ['raw applications', 'quick cooking'],
      flavor_impact: 'noticeable',
      texture_impact: 'noticeable',
      cooking_adjustment: 'Cooks faster than carrots. Sweeter flavor.',
    },
    {
      substitute_ingredient: 'butternut squash',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Similar sweetness and color. Different texture.',
      best_for: ['roasting', 'soups', 'purees'],
      avoid_for: ['stir-fries', 'raw applications'],
      flavor_impact: 'noticeable',
      texture_impact: 'noticeable',
    },
  ],
};

const BELL_PEPPER: StaticSubstitutionEntry = {
  ingredient: 'bell pepper',
  aliases: ['sweet pepper', 'capsicum', 'red bell pepper', 'green bell pepper'],
  category: 'vegetable',
  substitutions: [
    {
      substitute_ingredient: 'poblano pepper',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.8,
      reason: 'Similar texture with mild heat. Adds depth of flavor.',
      best_for: ['Mexican dishes', 'roasting', 'stuffing'],
      avoid_for: ['heat-sensitive diners'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
      cooking_adjustment: 'Slightly spicy. Remove seeds for milder flavor.',
    },
    {
      substitute_ingredient: 'zucchini',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.65,
      reason: 'Similar water content. Different flavor and softer texture.',
      best_for: ['stir-fries', 'pasta sauces', 'casseroles'],
      avoid_for: ['raw applications', 'stuffed peppers'],
      flavor_impact: 'noticeable',
      texture_impact: 'noticeable',
    },
    {
      substitute_ingredient: 'tomatoes',
      ratio: '1:1',
      confidence: 'low',
      confidence_score: 0.5,
      reason: 'Adds sweetness and acidity. Very different texture.',
      best_for: ['sauces', 'stews'],
      avoid_for: ['stir-fries', 'raw applications'],
      flavor_impact: 'significant',
      texture_impact: 'significant',
      cooking_adjustment: 'Adds liquid. Different flavor profile.',
    },
  ],
};

const TOMATOES: StaticSubstitutionEntry = {
  ingredient: 'tomatoes',
  aliases: ['fresh tomatoes', 'tomato'],
  category: 'vegetable',
  substitutions: [
    {
      substitute_ingredient: 'canned tomatoes',
      ratio: '1 lb fresh = 1 (14 oz) can',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Often better for cooking. More consistent flavor year-round.',
      best_for: ['sauces', 'soups', 'stews'],
      avoid_for: ['salads', 'sandwiches', 'fresh applications'],
      flavor_impact: 'minimal',
      texture_impact: 'minimal',
      cooking_adjustment: 'Drain if too much liquid. Already cooked.',
    },
    {
      substitute_ingredient: 'tomato paste + water',
      ratio: '1 cup tomatoes = 1/4 cup paste + 3/4 cup water',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Concentrated tomato flavor. Lacks fresh texture.',
      best_for: ['sauces', 'soups'],
      avoid_for: ['salads', 'chunky sauces'],
      flavor_impact: 'noticeable',
      texture_impact: 'significant',
    },
    {
      substitute_ingredient: 'red bell pepper',
      ratio: '1:1',
      confidence: 'low',
      confidence_score: 0.5,
      reason: 'Provides sweetness and color. Lacks acidity.',
      best_for: ['salads', 'stir-fries'],
      avoid_for: ['tomato-based sauces', 'acidic dishes'],
      flavor_impact: 'significant',
      texture_impact: 'noticeable',
      cooking_adjustment: 'Add lemon juice for acidity.',
    },
  ],
};

const TOMATO_PASTE: StaticSubstitutionEntry = {
  ingredient: 'tomato paste',
  aliases: ['concentrated tomato paste'],
  category: 'condiment',
  substitutions: [
    {
      substitute_ingredient: 'ketchup',
      ratio: '1 tbsp paste = 2-3 tbsp ketchup',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Similar tomato base. Much sweeter and thinner.',
      best_for: ['sauces', 'stews'],
      avoid_for: ['dishes where sugar is unwanted'],
      flavor_impact: 'noticeable',
      texture_impact: 'minimal',
      cooking_adjustment: 'Reduce sugar in recipe. Use more to achieve thickness.',
    },
    {
      substitute_ingredient: 'tomato sauce (reduced)',
      ratio: '1 tbsp paste = 3-4 tbsp tomato sauce (simmered)',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Same base ingredient. Just needs concentration.',
      best_for: ['all applications'],
      avoid_for: [],
      flavor_impact: 'none',
      texture_impact: 'none',
      cooking_adjustment: 'Simmer tomato sauce to reduce and concentrate.',
    },
    {
      substitute_ingredient: 'sun-dried tomatoes (pureed)',
      ratio: '1 tbsp paste = 2 tbsp rehydrated sun-dried tomatoes',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Concentrated tomato flavor with deeper, sweeter notes.',
      best_for: ['pasta sauces', 'Mediterranean dishes'],
      avoid_for: [],
      flavor_impact: 'noticeable',
      texture_impact: 'minimal',
      cooking_adjustment: 'Rehydrate and puree. More complex flavor.',
    },
  ],
};

/**
 * ADDITIONAL HERBS & SPICES
 */
const THYME: StaticSubstitutionEntry = {
  ingredient: 'thyme',
  aliases: ['fresh thyme', 'thyme leaves', 'dried thyme'],
  category: 'herb',
  substitutions: [
    {
      substitute_ingredient: 'oregano',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.8,
      reason: 'Similar earthy, woodsy profile. Common in Mediterranean cuisine.',
      best_for: ['roasted meats', 'vegetables', 'tomato-based dishes'],
      avoid_for: ['French cuisine', 'delicate fish'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'rosemary',
      ratio: '1 tsp thyme = 1/2 tsp rosemary',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Similar woody character. Much stronger and more piney.',
      best_for: ['roasted meats', 'potatoes', 'bread'],
      avoid_for: ['fish', 'delicate dishes'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
      cooking_adjustment: 'Use half the amount. Rosemary is more potent.',
    },
    {
      substitute_ingredient: 'marjoram',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Closely related herb. Sweeter and more delicate than thyme.',
      best_for: ['poultry', 'vegetables', 'soups'],
      avoid_for: ['heavily thyme-flavored dishes'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
  ],
};

const ROSEMARY: StaticSubstitutionEntry = {
  ingredient: 'rosemary',
  aliases: ['fresh rosemary', 'rosemary leaves'],
  category: 'herb',
  substitutions: [
    {
      substitute_ingredient: 'thyme',
      ratio: '1 tsp rosemary = 2 tsp thyme',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Similar woody character. Much milder than rosemary.',
      best_for: ['roasted meats', 'vegetables'],
      avoid_for: ['rosemary-focused dishes'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
      cooking_adjustment: 'Double the amount. Thyme is milder.',
    },
    {
      substitute_ingredient: 'sage',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Similar strong, earthy flavor. Different aroma.',
      best_for: ['pork', 'poultry', 'stuffing'],
      avoid_for: ['Italian dishes', 'lamb'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'bay leaves',
      ratio: '1 sprig rosemary = 2 bay leaves',
      confidence: 'low',
      confidence_score: 0.6,
      reason: 'Provides aromatic depth. Very different flavor.',
      best_for: ['soups', 'stews', 'braising'],
      avoid_for: ['grilling', 'roasting'],
      flavor_impact: 'significant',
      texture_impact: 'none',
      cooking_adjustment: 'Remove bay leaves before serving.',
    },
  ],
};

const MINT: StaticSubstitutionEntry = {
  ingredient: 'mint',
  aliases: ['fresh mint', 'mint leaves', 'peppermint', 'spearmint'],
  category: 'herb',
  substitutions: [
    {
      substitute_ingredient: 'basil',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.65,
      reason: 'Provides fresh, aromatic notes. Different flavor profile.',
      best_for: ['salads', 'fruit dishes'],
      avoid_for: ['Middle Eastern dishes', 'mojitos'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'cilantro',
      ratio: '1:1',
      confidence: 'low',
      confidence_score: 0.5,
      reason: 'Fresh, herbaceous quality. Very different taste.',
      best_for: ['salads', 'Thai dishes'],
      avoid_for: ['desserts', 'drinks', 'Middle Eastern cuisine'],
      flavor_impact: 'significant',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'mint extract',
      ratio: '1/4 cup mint = 1/4 tsp extract',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Concentrated mint flavor. No texture.',
      best_for: ['desserts', 'drinks'],
      avoid_for: ['savory dishes', 'garnishes'],
      flavor_impact: 'minimal',
      texture_impact: 'significant',
      cooking_adjustment: 'Very concentrated. Use sparingly (1/4 tsp per 1/4 cup fresh).',
    },
  ],
};

const DILL: StaticSubstitutionEntry = {
  ingredient: 'dill',
  aliases: ['fresh dill', 'dill weed', 'dill fronds'],
  category: 'herb',
  substitutions: [
    {
      substitute_ingredient: 'fennel fronds',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.8,
      reason: 'Similar anise-like flavor. Slightly sweeter.',
      best_for: ['fish', 'salads', 'pickles'],
      avoid_for: [],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'tarragon',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Anise-like flavor with more complexity. Stronger taste.',
      best_for: ['fish', 'chicken', 'sauces'],
      avoid_for: ['pickles', 'dishes where dill is prominent'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'parsley + celery seed',
      ratio: '1 tbsp dill = 1 tbsp parsley + pinch celery seed',
      confidence: 'low',
      confidence_score: 0.6,
      reason: 'Mimics freshness and subtle anise notes.',
      best_for: ['salads', 'dressings'],
      avoid_for: ['pickles', 'Scandinavian dishes'],
      flavor_impact: 'noticeable',
      texture_impact: 'minimal',
    },
  ],
};

const CHIVES: StaticSubstitutionEntry = {
  ingredient: 'chives',
  aliases: ['fresh chives'],
  category: 'herb',
  substitutions: [
    {
      substitute_ingredient: 'green onion tops',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Nearly identical onion flavor. Slightly stronger.',
      best_for: ['garnish', 'baked potatoes', 'dips'],
      avoid_for: [],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'shallots (minced)',
      ratio: '1 tbsp chives = 1 tsp minced shallot',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Similar mild onion flavor. Stronger and no green color.',
      best_for: ['cooked dishes', 'vinaigrettes'],
      avoid_for: ['garnish', 'dishes needing green color'],
      flavor_impact: 'noticeable',
      texture_impact: 'minimal',
      cooking_adjustment: 'Use less (1/3 amount). Stronger flavor.',
    },
    {
      substitute_ingredient: 'onion powder',
      ratio: '1 tbsp chives = 1/4 tsp onion powder',
      confidence: 'low',
      confidence_score: 0.5,
      reason: 'Provides onion flavor without texture or color.',
      best_for: ['cooked dishes', 'dips'],
      avoid_for: ['garnish', 'fresh applications'],
      flavor_impact: 'minimal',
      texture_impact: 'significant',
    },
  ],
};

const CAYENNE_PEPPER: StaticSubstitutionEntry = {
  ingredient: 'cayenne pepper',
  aliases: ['cayenne', 'ground cayenne'],
  category: 'spice',
  substitutions: [
    {
      substitute_ingredient: 'red pepper flakes',
      ratio: '1/2 tsp cayenne = 1 tsp red pepper flakes',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Similar heat level. Adds texture from flakes.',
      best_for: ['pasta', 'pizza', 'stir-fries'],
      avoid_for: ['smooth sauces', 'baking'],
      flavor_impact: 'minimal',
      texture_impact: 'noticeable',
    },
    {
      substitute_ingredient: 'hot paprika',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Similar heat with more complex flavor. Slightly less spicy.',
      best_for: ['Hungarian dishes', 'rubs', 'sauces'],
      avoid_for: [],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'chili powder',
      ratio: '1/2 tsp cayenne = 1 tsp chili powder',
      confidence: 'medium',
      confidence_score: 0.65,
      reason: 'Contains cayenne plus other spices. More complex.',
      best_for: ['Mexican dishes', 'chili'],
      avoid_for: ['pure heat needed'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
      cooking_adjustment: 'Contains cumin and other spices.',
    },
  ],
};

const ALLSPICE: StaticSubstitutionEntry = {
  ingredient: 'allspice',
  aliases: ['ground allspice', 'allspice berries'],
  category: 'spice',
  substitutions: [
    {
      substitute_ingredient: 'cinnamon + nutmeg + cloves',
      ratio: '1 tsp allspice = 1/2 tsp cinnamon + 1/4 tsp nutmeg + 1/4 tsp cloves',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Mimics the combination flavors allspice naturally has.',
      best_for: ['baking', 'pumpkin spice', 'Caribbean dishes'],
      avoid_for: [],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'cinnamon',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Dominant flavor in allspice. Lacks complexity.',
      best_for: ['baking', 'simple dishes'],
      avoid_for: ['complex spice blends', 'Caribbean cuisine'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'pumpkin pie spice',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Contains allspice plus other warm spices.',
      best_for: ['baking', 'fall recipes'],
      avoid_for: ['savory dishes'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
  ],
};

/**
 * ADDITIONAL SWEETENERS & EXTRACTS
 */
const HONEY: StaticSubstitutionEntry = {
  ingredient: 'honey',
  aliases: ['raw honey', 'liquid honey'],
  category: 'sweetener',
  substitutions: [
    {
      substitute_ingredient: 'maple syrup',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Similar liquid sweetness. Different flavor profile.',
      best_for: ['baking', 'glazes', 'breakfast'],
      avoid_for: ['recipes where honey flavor is important'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'agave nectar',
      ratio: '3/4 cup agave = 1 cup honey',
      confidence: 'high',
      confidence_score: 0.8,
      reason: 'Similar consistency. Sweeter than honey.',
      best_for: ['beverages', 'glazes', 'marinades'],
      avoid_for: [],
      flavor_impact: 'minimal',
      texture_impact: 'none',
      cooking_adjustment: 'Reduce amount by 25%. Sweeter than honey.',
    },
    {
      substitute_ingredient: 'sugar + water',
      ratio: '1 cup honey = 1 1/4 cup sugar + 1/4 cup water',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Provides sweetness and moisture. Lacks honey flavor.',
      best_for: ['baking'],
      avoid_for: ['glazes', 'dressings', 'honey-flavored dishes'],
      flavor_impact: 'noticeable',
      texture_impact: 'minimal',
    },
  ],
};

const VANILLA_EXTRACT: StaticSubstitutionEntry = {
  ingredient: 'vanilla extract',
  aliases: ['pure vanilla extract', 'vanilla'],
  category: 'extract',
  substitutions: [
    {
      substitute_ingredient: 'vanilla bean paste',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.95,
      reason: 'More intense vanilla flavor with visible seeds. Premium option.',
      best_for: ['custards', 'ice cream', 'baking'],
      avoid_for: [],
      flavor_impact: 'none',
      texture_impact: 'minimal',
    },
    {
      substitute_ingredient: 'vanilla bean',
      ratio: '1 tsp extract = 1 inch vanilla bean',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Pure, intense vanilla flavor. More expensive.',
      best_for: ['custards', 'puddings', 'ice cream'],
      avoid_for: ['quick recipes'],
      flavor_impact: 'none',
      texture_impact: 'none',
      cooking_adjustment: 'Split and scrape seeds. Steep in liquid.',
    },
    {
      substitute_ingredient: 'almond extract',
      ratio: '1 tsp vanilla = 1/2 tsp almond',
      confidence: 'low',
      confidence_score: 0.5,
      reason: 'Different flavor. Adds aromatic sweetness.',
      best_for: ['baking', 'cookies', 'cakes'],
      avoid_for: ['vanilla-focused recipes'],
      flavor_impact: 'significant',
      texture_impact: 'none',
      cooking_adjustment: 'Use half the amount. Much stronger.',
    },
  ],
};

/**
 * ADDITIONAL LIQUIDS & ACIDS
 */
const LIME_JUICE: StaticSubstitutionEntry = {
  ingredient: 'lime juice',
  aliases: ['fresh lime juice', 'lime'],
  category: 'acid',
  substitutions: [
    {
      substitute_ingredient: 'lemon juice',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.95,
      reason: 'Similar acidity. Slightly sweeter and less bitter.',
      best_for: ['dressings', 'marinades', 'beverages'],
      avoid_for: ['lime-focused dishes', 'Mexican/Thai cuisine'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'white wine vinegar',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Similar acidity. Lacks citrus flavor.',
      best_for: ['dressings', 'marinades'],
      avoid_for: ['drinks', 'desserts'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'rice vinegar',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Milder acidity. Works in Asian dishes.',
      best_for: ['Asian cuisine', 'dressings'],
      avoid_for: ['Mexican dishes', 'drinks'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
    },
  ],
};

const RICE_VINEGAR: StaticSubstitutionEntry = {
  ingredient: 'rice vinegar',
  aliases: ['rice wine vinegar', 'seasoned rice vinegar'],
  category: 'acid',
  substitutions: [
    {
      substitute_ingredient: 'apple cider vinegar + sugar',
      ratio: '1 tbsp rice vinegar = 1 tbsp ACV + 1/4 tsp sugar',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Similar mild acidity and sweetness.',
      best_for: ['Asian dishes', 'sushi rice', 'dressings'],
      avoid_for: [],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'white wine vinegar + sugar',
      ratio: '1 tbsp rice vinegar = 1 tbsp white wine vinegar + 1/4 tsp sugar',
      confidence: 'high',
      confidence_score: 0.8,
      reason: 'Mimics mild sweetness of rice vinegar.',
      best_for: ['sushi rice', 'dressings', 'marinades'],
      avoid_for: [],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'lime juice',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Provides acidity with citrus brightness.',
      best_for: ['Asian dishes', 'dressings'],
      avoid_for: ['sushi rice'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
    },
  ],
};

const BALSAMIC_VINEGAR: StaticSubstitutionEntry = {
  ingredient: 'balsamic vinegar',
  aliases: ['balsamic', 'aged balsamic'],
  category: 'acid',
  substitutions: [
    {
      substitute_ingredient: 'red wine vinegar + sugar',
      ratio: '1 tbsp balsamic = 1 tbsp red wine vinegar + 1/2 tsp sugar',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Mimics sweet-tart balance of balsamic.',
      best_for: ['dressings', 'marinades', 'reductions'],
      avoid_for: ['dishes where balsamic is the star'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'sherry vinegar',
      ratio: '1:1',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Complex, slightly sweet acidity. Different flavor.',
      best_for: ['vinaigrettes', 'sauces'],
      avoid_for: ['balsamic reductions'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'worcestershire sauce',
      ratio: '1:1',
      confidence: 'low',
      confidence_score: 0.6,
      reason: 'Provides depth and tang. Very different flavor.',
      best_for: ['marinades', 'savory dishes'],
      avoid_for: ['salads', 'sweet applications'],
      flavor_impact: 'significant',
      texture_impact: 'none',
    },
  ],
};

const WHITE_WINE: StaticSubstitutionEntry = {
  ingredient: 'white wine',
  aliases: ['dry white wine', 'cooking wine'],
  category: 'liquid',
  substitutions: [
    {
      substitute_ingredient: 'chicken broth + lemon juice',
      ratio: '1 cup wine = 1 cup broth + 1 tbsp lemon juice',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Provides acidity and flavor. Non-alcoholic.',
      best_for: ['sauces', 'risotto', 'braising'],
      avoid_for: ['wine-focused dishes'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'white wine vinegar + water',
      ratio: '1 cup wine = 2 tbsp vinegar + 1 cup water',
      confidence: 'high',
      confidence_score: 0.8,
      reason: 'Mimics acidity. No alcohol.',
      best_for: ['deglazing', 'sauces', 'marinades'],
      avoid_for: [],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'vermouth',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Similar acidity with herbal notes. Actually better for cooking.',
      best_for: ['sauces', 'deglazing', 'risotto'],
      avoid_for: [],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
  ],
};

const BUTTERMILK: StaticSubstitutionEntry = {
  ingredient: 'buttermilk',
  aliases: ['cultured buttermilk', 'low-fat buttermilk'],
  category: 'dairy',
  substitutions: [
    {
      substitute_ingredient: 'milk + lemon juice',
      ratio: '1 cup buttermilk = 1 cup milk + 1 tbsp lemon juice',
      confidence: 'high',
      confidence_score: 0.95,
      reason: 'Creates instant buttermilk substitute. Let sit 5 minutes to curdle.',
      best_for: ['baking', 'pancakes', 'biscuits'],
      avoid_for: ['drinking', 'cold applications'],
      flavor_impact: 'none',
      texture_impact: 'none',
      cooking_adjustment: 'Mix and let sit 5-10 minutes before using.',
    },
    {
      substitute_ingredient: 'milk + vinegar',
      ratio: '1 cup buttermilk = 1 cup milk + 1 tbsp white vinegar',
      confidence: 'high',
      confidence_score: 0.95,
      reason: 'Identical to lemon juice method.',
      best_for: ['baking', 'marinades'],
      avoid_for: [],
      flavor_impact: 'none',
      texture_impact: 'none',
      cooking_adjustment: 'Let sit 5 minutes to curdle.',
    },
    {
      substitute_ingredient: 'plain yogurt + milk',
      ratio: '1 cup buttermilk = 3/4 cup yogurt + 1/4 cup milk',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Similar tang and thickness. More protein.',
      best_for: ['baking', 'marinades', 'dressings'],
      avoid_for: [],
      flavor_impact: 'minimal',
      texture_impact: 'minimal',
    },
  ],
};

const CHICKEN_BROTH: StaticSubstitutionEntry = {
  ingredient: 'chicken broth',
  aliases: ['chicken stock', 'low-sodium chicken broth'],
  category: 'liquid',
  substitutions: [
    {
      substitute_ingredient: 'vegetable broth',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Similar savory depth. Vegetarian-friendly.',
      best_for: ['soups', 'risotto', 'sauces'],
      avoid_for: ['chicken-focused dishes'],
      flavor_impact: 'minimal',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'bouillon cube + water',
      ratio: '1 cup broth = 1 cube + 1 cup hot water',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Concentrated broth. Watch salt levels.',
      best_for: ['all applications'],
      avoid_for: [],
      flavor_impact: 'none',
      texture_impact: 'none',
      cooking_adjustment: 'Often very salty. Adjust seasoning.',
    },
    {
      substitute_ingredient: 'water + soy sauce',
      ratio: '1 cup broth = 1 cup water + 1 tsp soy sauce',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Adds umami depth. Different flavor profile.',
      best_for: ['Asian dishes', 'stir-fries'],
      avoid_for: ['light-colored sauces'],
      flavor_impact: 'noticeable',
      texture_impact: 'none',
    },
  ],
};

/**
 * BAKING ESSENTIALS
 */
const BAKING_POWDER: StaticSubstitutionEntry = {
  ingredient: 'baking powder',
  aliases: ['double-acting baking powder'],
  category: 'leavening',
  substitutions: [
    {
      substitute_ingredient: 'baking soda + cream of tartar',
      ratio: '1 tsp = 1/4 tsp baking soda + 1/2 tsp cream of tartar',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Baking powder is essentially this combination.',
      best_for: ['all baking applications'],
      avoid_for: [],
      flavor_impact: 'none',
      texture_impact: 'none',
    },
    {
      substitute_ingredient: 'baking soda + lemon juice',
      ratio: '1 tsp = 1/4 tsp baking soda + 1/2 tsp lemon juice',
      confidence: 'medium',
      confidence_score: 0.75,
      reason: 'Acid + base reaction creates leavening.',
      best_for: ['quick breads', 'pancakes'],
      avoid_for: ['delicate cakes'],
      flavor_impact: 'minimal',
      texture_impact: 'minimal',
      cooking_adjustment: 'Mix and add immediately as reaction begins right away.',
    },
    {
      substitute_ingredient: 'self-rising flour',
      ratio: 'use self-rising flour and omit baking powder + salt',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Already contains baking powder and salt.',
      best_for: ['biscuits', 'quick breads'],
      avoid_for: ['yeast breads', 'recipes with specific flour types'],
      flavor_impact: 'none',
      texture_impact: 'minimal',
      cooking_adjustment: 'Contains 1.5 tsp baking powder + 1/4 tsp salt per cup flour.',
    },
  ],
};

const BAKING_SODA: StaticSubstitutionEntry = {
  ingredient: 'baking soda',
  aliases: ['sodium bicarbonate', 'bicarbonate of soda'],
  category: 'leavening',
  substitutions: [
    {
      substitute_ingredient: 'baking powder',
      ratio: '1 tsp soda = 3 tsp baking powder',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Baking powder is weaker. Need more and won\'t neutralize acid.',
      best_for: ['recipes without acidic ingredients'],
      avoid_for: ['recipes with buttermilk, yogurt, vinegar'],
      flavor_impact: 'minimal',
      texture_impact: 'noticeable',
      cooking_adjustment: 'Triple the amount. May affect taste and texture.',
    },
  ],
};

const ALL_PURPOSE_FLOUR: StaticSubstitutionEntry = {
  ingredient: 'all-purpose flour',
  aliases: ['ap flour', 'plain flour', 'white flour'],
  category: 'flour',
  substitutions: [
    {
      substitute_ingredient: 'whole wheat flour',
      ratio: '1 cup AP = 7/8 cup whole wheat',
      confidence: 'medium',
      confidence_score: 0.7,
      reason: 'Healthier with more fiber. Denser texture.',
      best_for: ['bread', 'muffins', 'pancakes'],
      avoid_for: ['cakes', 'pastries', 'delicate baking'],
      flavor_impact: 'noticeable',
      texture_impact: 'noticeable',
      cooking_adjustment: 'Heavier and denser. Add extra liquid or use 50/50 blend.',
    },
    {
      substitute_ingredient: 'bread flour',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Higher protein content. Better for bread, chewier for other baking.',
      best_for: ['bread', 'pizza dough', 'bagels'],
      avoid_for: ['cakes', 'pastries'],
      flavor_impact: 'none',
      texture_impact: 'minimal',
      cooking_adjustment: 'Creates chewier texture due to more gluten.',
    },
    {
      substitute_ingredient: 'oat flour',
      ratio: '1 cup AP = 1 1/3 cup oat flour',
      confidence: 'medium',
      confidence_score: 0.65,
      reason: 'Gluten-free alternative. Adds sweetness and moisture.',
      best_for: ['muffins', 'cookies', 'pancakes'],
      avoid_for: ['bread', 'recipes needing gluten structure'],
      flavor_impact: 'noticeable',
      texture_impact: 'noticeable',
      cooking_adjustment: 'No gluten. Add binding agent like xanthan gum.',
    },
  ],
};

/**
 * THICKENERS
 */
const CORNSTARCH: StaticSubstitutionEntry = {
  ingredient: 'cornstarch',
  aliases: ['corn starch', 'cornflour (UK)'],
  category: 'thickener',
  substitutions: [
    {
      substitute_ingredient: 'all-purpose flour',
      ratio: '1 tbsp cornstarch = 2 tbsp flour',
      confidence: 'high',
      confidence_score: 0.85,
      reason: 'Common thickener. Less potent than cornstarch.',
      best_for: ['gravies', 'sauces', 'soups'],
      avoid_for: ['glazes', 'clear sauces'],
      flavor_impact: 'minimal',
      texture_impact: 'minimal',
      cooking_adjustment: 'Double the amount. Cook longer to remove flour taste.',
    },
    {
      substitute_ingredient: 'arrowroot powder',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Neutral flavor, creates clear sauces. Great for acidic dishes.',
      best_for: ['fruit sauces', 'glazes', 'acidic dishes'],
      avoid_for: ['dairy-based sauces'],
      flavor_impact: 'none',
      texture_impact: 'none',
      cooking_adjustment: 'Add at end of cooking. Doesn\'t tolerate prolonged heat.',
    },
    {
      substitute_ingredient: 'tapioca starch',
      ratio: '1:1',
      confidence: 'high',
      confidence_score: 0.9,
      reason: 'Gluten-free, creates glossy finish. Freezes well.',
      best_for: ['pies', 'fruit fillings', 'sauces'],
      avoid_for: [],
      flavor_impact: 'none',
      texture_impact: 'none',
      cooking_adjustment: 'Creates glossier finish than cornstarch.',
    },
  ],
};

/**
 * COMPLETE STATIC LIBRARY - Export all substitutions
 *
 * Coverage: 54 ingredients with 160+ substitution options
 */
export const STATIC_SUBSTITUTION_LIBRARY: StaticSubstitutionEntry[] = [
  // Fats & Oils (4 ingredients)
  BUTTER,
  OLIVE_OIL,
  VEGETABLE_OIL,
  COCONUT_OIL,

  // Dairy (5 ingredients)
  MILK,
  HEAVY_CREAM,
  SOUR_CREAM,
  EGGS,
  BUTTERMILK,

  // Condiments & Sauces (6 ingredients)
  MAYONNAISE,
  DIJON_MUSTARD,
  SOY_SAUCE,
  WORCESTERSHIRE_SAUCE,
  TOMATO_PASTE,

  // Acids & Vinegars (5 ingredients)
  LEMON_JUICE,
  LIME_JUICE,
  VINEGAR_WHITE,
  RICE_VINEGAR,
  BALSAMIC_VINEGAR,

  // Proteins (2 ingredients)
  CHICKEN_BREAST,
  GROUND_BEEF,

  // Vegetables (5 ingredients)
  CELERY,
  CARROTS,
  BELL_PEPPER,
  TOMATOES,

  // Aromatics (3 ingredients)
  GARLIC,
  ONION,
  GINGER,

  // Fresh Herbs (8 ingredients)
  BASIL,
  OREGANO,
  CILANTRO,
  PARSLEY,
  THYME,
  ROSEMARY,
  MINT,
  DILL,
  CHIVES,

  // Spices (5 ingredients)
  CUMIN,
  PAPRIKA,
  CINNAMON,
  CAYENNE_PEPPER,
  ALLSPICE,

  // Sweeteners & Extracts (4 ingredients)
  SUGAR,
  BROWN_SUGAR,
  HONEY,
  VANILLA_EXTRACT,

  // Liquids (2 ingredients)
  WHITE_WINE,
  CHICKEN_BROTH,

  // Baking Essentials (4 ingredients)
  BAKING_POWDER,
  BAKING_SODA,
  ALL_PURPOSE_FLOUR,
  CORNSTARCH,
];

/**
 * Get substitution count for reporting
 */
export function getLibraryStats() {
  const totalIngredients = STATIC_SUBSTITUTION_LIBRARY.length;
  const totalSubstitutions = STATIC_SUBSTITUTION_LIBRARY.reduce(
    (sum, entry) => sum + entry.substitutions.length,
    0
  );

  const categories = STATIC_SUBSTITUTION_LIBRARY.reduce((acc, entry) => {
    acc[entry.category] = (acc[entry.category] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  return {
    totalIngredients,
    totalSubstitutions,
    categories,
  };
}
